<?php
$baseUrl = $this->getBaseUrl();
?>
<div class="privacy-content">
<div class="breadcrumbs"><a href="<?php echo $baseUrl; ?>">Home</a><Span class="breadcrumb-name">> Privacy Policy</span></div>
<div class="privacy-banner">
        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Privacypolicy::images/privacy-policy.svg'); ?>" alt="MedizinHub Editorial Policy">
</div>
<h1 class="privacy-title">MedizinHub Privacy Policy</h1>
<p class="privacy-description">At <strong>Medizinhub Pharmacy Private Limited</strong> (&quot;Medizinhub&quot; or &quot;we&quot;), we are
committed to protecting your personal information. This Privacy Notice explains the
types of personal data we collect from you when you use our website (including sub-
domains and microsites) or mobile applications. It outlines why we collect this
information, who we may share it with, and the steps we take to ensure its security.
Additionally, it informs you about your rights regarding your personal data and the
choices available to you. It also explains how you can reach us to discuss our
privacy practices.<br>We encourage you to carefully review this Privacy Notice before accessing or using
any of our products or services.</p>
<h2 class="privacy-title">1.GENERAL TERMS</h2>
<p class="privacy-description">By accessing or using the Platform or Services, or by providing us with your
information, you confirm that you have the legal capacity to enter into a binding
contract under Indian law, specifically the Indian Contract Act, 1872. You
acknowledge that you have read, understood, and agreed to the practices and
policies outlined in this Privacy Policy and agree to be bound by its terms.<br>You consent to our collection, use, sharing, and disclosure of your information as
described in this Privacy Policy. We reserve the right to change, modify, add, or
remove portions of this Privacy Policy at our discretion, at any time. Continued use of
the App, Services, or Platform following any amendments will be considered your
implicit acceptance of the updated Privacy Policy. We encourage you to review this
Privacy Policy periodically to stay informed of any changes.<br>If you are accessing or using the Services on the App or the Site from a location
outside of India, you do so at your own risk and are solely responsible for complying
with any applicable local laws.<br>If you do not agree with any terms or conditions of this Privacy Policy, please refrain
from using the Site, App, or any Services. This Privacy Policy may change at any
time without prior notice, so we recommend that you check this policy regularly on
the Site or App to remain informed of any updates.</p>
<h2 class="privacy-title">2. WHAT INFORMATION DO WE COLLECT ABOUT YOU?</h2>
<p class="privacy-description">We collect different types of information to provide and improve our services,
including:</p>
<ol type="A">
<li><strong>Personal Details: </strong>This encompasses your age, gender, date of birth, marital
status, nationality, government ID details, occupation, ethnicity, religion, travel
history, and any other information you provide through surveys or
questionnaires.</li>
<li><strong>Health and Medical Information: </strong>This includes prescription details, medical
history, and any other health-related data necessary for providing our
services.</</li>
<li><strong>Technical Data: </strong>Information about your device, IP address, browser type,
and usage patterns when you interact with our website or mobile apps.</</li>
<li><strong>Transaction Information: </strong>Details of your purchases, orders, and payment
history.</</li>
<li><strong>Location Data: </strong>If you allow us, we may collect location information to improve
our services, such as finding nearby pharmacies or delivery options..</</li>
<li><strong>Payment and Transaction Data: </strong>We collect data related to your payment
methods, transaction history, preferences, spending patterns, and other
financial details like payment instruments and modes of payment.</</li>
<li><strong>Customer Reviews and Opinions: </strong>We collect your reviews, opinions, and
feedback about our products, services, and programs.</</li>
<li><strong>Rewards and Membership Information: </strong>This includes your membership
details, account information, profile or password data, and any affiliations with
frequent flyer or travel partner programs.</</li>
</ol>
<p class="privacy-description">We collect this information to enhance your experience and ensure the proper
functioning of our services.</p>
<h2 class="privacy-title">3. HOW WE USE THE INFORMATION WE COLLECT</h2>
<p class="privacy-description">We use the information we collect in various ways to provide our Services on the
App and the Site and to operate our business, including:</p>
<ol type="A">
<li><strong>Fulfillment of Requests: </strong>To carry out our obligations arising from your
requests for products and Services on the Platform.</li>
<li><strong>Platform Improvement: </strong>To operate and enhance the Platform, fostering a
positive user experience and improving our overall business.</</li>
<li><strong>Order Processing: </strong>To process and deliver your orders.</</li>
<li><strong>Access Enablement: </strong>To grant you access to our Site or App for purchasing
products and receiving Services.</</li>
<li><strong>Consultation Facilitation: </strong>To enable you to initiate consultations with
Medical Practitioners or facilitate diagnostic tests.</</li>
<li><strong>Data Analysis: </strong>To analyze data, track trends, build algorithms, and create
databases for rating systems and recommendation engines.</</li>
<li><strong>Research and Development: </strong>For growth and development of our business
and that of our group entities, including expanding our network of consulting
RMPs/doctors and partners.</</li>
<li><strong>Customer Service: </strong>To respond to your requests, customize your orders,
improve our Platform, and communicate with you.</</li>
<li><strong>Compliance and Auditing: </strong>For non-targeting purposes such as frequency
capping, compliance, billing, ad reporting, market research, product
development, and to comply with applicable laws.</</li>
<li><strong>Quality Assurance: </strong>To conduct audits and quality assessment procedures.</</li>
<li><strong>Resource Analysis: </strong>To analyze the use of our resources, troubleshoot
problems, and improve our Products and Services, utilizing information
regarding your mobile device and software.</</li>
<li><strong>User Communication: </strong>To contact users, both during and after an order, for
updates, query resolution, order details, consultations, follow-ups, or to offer
new products and Services.</</li>
<li><strong>Fraud Prevention: </strong>To investigate, prevent, or take action regarding illegal
activities, suspected fraud, threats to safety, violations of our Terms, or as
required by law.</</li>
<li><strong>User Queries: </strong>To respond to your queries and communicate information,
including promotions, updates to the Site, or future fees for purchasing
products or Services.</</li>
<li><strong>Feedback Collection: </strong>To contact you via SMS, email, and phone calls for
your valuable feedback on our current and potential products and Services.</</li>
<li><strong>Abandoned Carts: </strong>If you add products to your cart but do not complete the
checkout process, we may contact you via SMS, email, or phone to assist you
in completing your order.</</li>
<li><strong>Cookie Usage: </strong>We may use cookies and automatically collected information
to (i) personalize our services, such as remembering your information for
future visits; (ii) provide customized advertisements, content, and information;
(iii) monitor and analyze the effectiveness of our Services and third-party
marketing; (iv) track aggregate site usage metrics; and (v) manage your
entries and submissions in promotions or other activities.</</li>
<li><strong>Fraud Detection: </strong>We may access or store your information as necessary to
detect, prevent, or address fraud and illegal activities or to protect the rights
and safety of the Platform and others.</</li>
<li><strong>Location Information: </strong>We may use information about your location to
confirm you are in a jurisdiction where the Service is offered and to identify
appropriate Medical Practitioners.</</li>
<li><strong>De-identified Information: </strong>We may collect, analyze, use, publish, and sell
de-identified information, which may include components of your personal or
sensitive information, for any lawful business purpose, including research and
marketing.</</li>
</ol>
<h2 class="privacy-title">4. DATA YOU SHARE</h2>
<p class="privacy-description">Medizinhub may collect your data in various ways through your interactions with our
stores, website, or mobile application. For example:</p>
<ol type="A">
<li>When you register with us to receive our products and/or services.</li>
<li>When you complete a transaction or attempt to transact at our stores, on our
website, or through our mobile application.</li>
<li>When you participate in surveys conducted by or on behalf of us.</li>
<li>When you choose to receive communications from us, including promotional
offers.</li>
<li>From the information gathered during your visits to our stores, website, or
mobile application.</li>
</ol>
<h2 class="privacy-help-text">DISCLOSURE OF YOUR INFORMATION</h2>
<p class="privacy-description">Information about you and other users of the Platform is a vital part of our business.
We share personal information only as described below, ensuring that any third party
has implemented adequate data protection measures and adheres to practices at
least as protective as those outlined in this Privacy Policy. By using the Site or the
App, you accept these terms and consent to the storage and processing of your
personal information and sensitive personal data (SPDI) by third parties.<br>We have arrangements with various third parties, including affiliates, service
providers, retailers, retail pharmacies, payment gateways, and logistics partners,
who may have access to your personal information and SPDI. However, they are
prohibited from disclosing this information to any other individual or entity. Some of
these third parties include:</p>
<ol type="A">
<li><strong>Retail Partners: </strong>Your personal information or SPDI may be shared with
affiliated retailers and retail pharmacies that fulfill your orders and with
Medical Practitioners. These retailers operate on the Platform or sell
medicines and wellness products through the Site or the App. You will be
informed when a third party is involved in your transactions, and we will share
relevant customer information with them.</</li>
<li><strong>Third-Party Service Providers: </strong>Your personal information or SPDI may also
be shared with third-party service providers, such as diagnostic service
providers (including labs and collection agents), retailers, and logistics
providers, to fulfill services and deliver your orders. This includes processing
orders, facilitating diagnostic tests, delivering packages, sending newsletters
and emails, analyzing data, and providing customer service. These service
providers may collect personal information necessary for their functions and
must process this information according to this Privacy Policy and applicable
laws. Please note that we are not responsible for the actions or omissions of
these third parties, but we will assist you in resolving any issues that may
arise with them.</</li>
<li><strong>Legal Obligations: </strong>We may release account and other personal information
when we believe it is appropriate to comply with applicable laws. This may
include conforming to legal requirements, protecting rights or property,
preventing crimes, or ensuring the safety of our users or the public. We may
also disclose your personal information to enforce our Terms and agreements
or protect our rights and those of others.</</li>
<li>Mergers, Amalgamations, or Transfers: In the event of a merger, acquisition,
or transfer of our assets, the third party involved will have the right to continue
using your information (including SPDI) in accordance with this Privacy Policy.
We may also share information with partners, affiliates, or potential associates
in an anonymized and aggregated manner for understanding user interactions
and enhancing the overall experience.</</li>
<li>Business Improvement: You acknowledge that we have the right to use
recorded copies of your telephone conversations, e-prescriptions with Medical
Practitioners, and diagnostic test reports to improve our services, marketing
efforts, and customer experience. These uses help us tailor our Site, App, and
Services to better meet your needs. We may transfer such personal
information and SPDI to third parties, including those outside India, while
taking reasonable steps to ensure compliance with applicable data protection
laws.</</li>
</ol>
<h2 class="privacy-title">5. TRANSFER TO THIRD PARTIES AND OUTSIDE INDIA</h2>
<p class="privacy-description">Subject to applicable laws, we may, at our discretion, transfer personal information
and SPDI to any corporate entity (as defined under the Information Technology Act,
2000) that provides at least the same level of data protection as we do, whether
located in India or elsewhere.<br>By using the Site and the App, you consent to our sharing and processing of your
personal information and SPDI by third parties, including in locations outside India,
provided that they maintain protection standards comparable to those in India or
equivalent international standards.</p>
<h2 class="privacy-title">6. PROTECTING YOUR INFORMATION</h2>
<p class="privacy-description">We implement electronic, physical, and procedural safeguards to protect the
collection, storage, and disclosure of personal information, including sensitive
personal data (SPDI). As part of our security procedures, we may occasionally
request proof of identity before disclosing any personal information to you.
To safeguard your information during transmission, we utilize Secure Sockets Layer
(SSL) software, which encrypts the data you input. We also adhere to international
standards for information security management systems.<br>Access to personal information is restricted to our employees and agents who
require it to process information on our behalf. These individuals are bound by strict
confidentiality obligations and may face disciplinary action, including termination, for
failing to comply with these requirements.<br>No employee or administrator will have knowledge of your account password. It is
essential for you to protect your account from unauthorized access by securing your
password and mobile phone, as outlined in the ‘User Account, Password and
Security’ section of the Terms. Please remember to log off from the Site or the App
after use. We are not liable for any unauthorized use of your account or password.<br>If you suspect any unauthorized access to your account, you must notify us
immediately by sending an email to the contact details provided in the contact
section. You agree to indemnify us for any losses incurred due to unauthorized use
of your account or password.<br>In certain circumstances, we may not be able to obtain your prior consent before
disclosing your information if it is requested by government agencies or required by
law during investigations of cyber incidents or criminal prosecutions.<br>Furthermore, we are not responsible for any security breaches or actions taken by
third parties, or for events beyond our reasonable control, including government
actions, hacking, unauthorized access to data, computer crashes, or poor-quality
internet and phone services.</p>
<h2 class="privacy-title">7. YOUR DATA ACCESS OPTIONS</h2>
<p class="privacy-description">Through the Platform, you have the ability to access various details related to
your account and interactions. This includes viewing your personal information and,
where applicable, updating, modifying, or deleting data that you’ve provided. You can
correct any inaccurate or incomplete personal details, including sensitive personal
data, whenever feasible. Additionally, you can choose to opt-out of optional services, such as receiving promotional emails or offers. If you wish to opt-in to these services
during sign-up, you will be given the opportunity to do so.</p>
<h2 class="privacy-title">8. IS THE PLATFORM ACCESSIBLE TO CHILDREN?</h2>
<p class="privacy-description">The Platform is only accessible to individuals who can legally form a binding
contract under the Indian Contract Act, 1872. If you are under 18 years of age, you
are not permitted to use or access our services. If we become aware that anyone
under 18 has registered, used the platform, or provided personally identifiable
information, we will take steps to delete this information from our systems. Parents or
guardians who discover that their child under 18 has gained unauthorized access
can contact us at <a href="#">care@medizinhub.com</a> to request the deletion of the child’s
personal data.</p>
<h2 class="privacy-title">9. THIRD-PARTY LINKS</h2>
<p class="privacy-description">The Platform may contain hyperlinks to external websites, services,
advertisements, or other content (“Third-Party Links”) operated by entities not
associated with us. We do not control or endorse the practices or content of these
third-party platforms. You acknowledge that we are not responsible for the collection,
use, or disclosure of your information by these third parties.<br>Interactions or transactions between you and these third parties are solely
your responsibility. We cannot be held liable for any loss, damage, or disputes that
arise from such engagements. Additionally, we encourage you to review the privacy
policies and terms of these third-party platforms before sharing any personal data,
ensuring you make informed decisions when interacting with their services.</p>
<h2 class="privacy-title">10. DATA RETENTION</h2>
<p class="privacy-description">Medizinhub retains your data for as long as it is necessary to deliver our
products and services, maintain access to our website or mobile application, or fulfill
other important purposes such as complying with legal obligations, resolving
disputes, and enforcing agreements. The duration for which we retain your data may
vary depending on the type of data and its intended use, as well as the applicable
legal requirements. Retention periods are therefore subject to variation based on
these factors.<br>Even if you request deletion of your data, or if we delete it as part of routine
processes, some of your information may still be preserved on backup or archival
systems for purposes such as audits, legal compliance, tax requirements, or
regulatory needs.</p>
<h2 class="privacy-title">11. DATA STORAGE LOCATION</h2>
<p class="privacy-description">Data collected under this Privacy Notice is stored on servers located within India.</p>
<h2 class="privacy-title">12. DATA PROCESSING</h2>
<p class="privacy-description">We ensure that the data collected under this Privacy Notice is processed in
accordance with both its terms and applicable legal requirements. To provide
adequate protection for your data, we have established appropriate written
agreements with Medizinhub Entities, Partners, and Service Providers with whom
we share your information. These agreements ensure that your data is handled by
these parties in compliance with applicable law.</p>
<h2 class="privacy-title">12. DATA PROCESSING</h2>
<p class="privacy-description">During onboarding, we request the following app permissions to enhance your
experience:</p>
<ol type="A">
<li><strong>Location: </strong>We recommend allowing location sharing to &quot;Always&quot; so we can
provide location-specific data, such as product availability. You can change
this setting anytime.</li>
<li><strong>Camera: </strong>To let you take a photo of prescriptions and upload them directly to
the app.</li>
<li><strong>Photos/Media/Files: </strong>Required to store and retrieve your uploads, such as
prescriptions, on your device.</li>
<li><strong>SMS: </strong>Supports automatic OTP confirmation, so you don&#39;t have to manually
enter the authentication code.</li>
<li><strong>Receive SMS: </strong>Allows us to send payment-related SMS notifications through
our payment partner JustPay.</li>
<li><strong>Access Wi-Fi State: </strong>Helps optimize your experience based on Wi-Fi
strength, particularly for video consultations..</li>
<li><strong>Record Audio: </strong>Enables voice input during video consultations with doctors.</li>
<li><strong>Bluetooth: </strong>Used for connecting to Bluetooth headsets during video
consultations.</li>
</ol>
<h2 class="privacy-title">14.SEVERABILITY</h2>
<p class="privacy-description">If any court or competent authority determines that any provision of this Privacy
Notice, or part thereof, is invalid, illegal, or unenforceable, that provision (or part) will
be considered removed to the extent necessary, without affecting the validity of the
remaining provisions.</p>
<h2 class="privacy-title">15.UPDATES TO THIS PRIVACY NOTICE</h2>
<p class="privacy-description">As our business evolves, this Privacy Notice may be updated periodically. We may
send email reminders about such updates unless you&#39;ve opted out. However, we
encourage you to frequently review our website and mobile application to stay
informed of any changes. Any updates will be effective as soon as they are posted.
By continuing to use our website, mobile application, or services following these
updates, you agree to the revised terms of the Privacy Notice.</p>
<h2 class="privacy-title">16. CONTACT US</h2>
<p class="privacy-description">To request to access, review, update, or withdraw your consent for your personal
information or to otherwise reach us, please submit a request by e-mailing us
at <a href="#">care@medizinhub.com</a> You may contact us for information on Service
Providers, Partners with whom we may share your Data in compliance with this
Privacy Notice and applicable law. We will respond to your request within 30 days.</p>
<h2 class="privacy-title">17.GRIEVANCE OFFICER</h2>
<p class="privacy-description">Please see below the details of our grievance officer:</p>
<h2 class="privacy-title">Name: Mr. N. Balaji</h2>
<h2 class="privacy-title">Email:  support@medizinhub.com</h2>
<p class="privacy-description"><strong>Address: </strong>112, Bharath Flats, RadhaNagar Main Road, Chromepet, Chennai-600
044, Tamil Nadu, India</p>
<h2 class="privacy-title">Mobile Number: 9047660909</h2>
</div>