<?php
  $baseUrl = $this->getBaseUrl();
?>
<div class="refund-content">
    <div class="breadcrumbs" ><a href="<?php echo $baseUrl; ?>">Home</a> <Span class="breadcrumb-name"> > Return & Refund Policy</span></div>   
    <div class="refund-header">Return and Refund Policy</div>
    <div class="refund-title">Cancellation Policy</div>
    <div class="refund-subtitle">1. How can I cancel an order?</div>
    <div class="refund-helptext">1.1 Medicines and Healthcare Products</div>
    <div class="refund-description">An order for medicines or healthcare products can be cancelled from the ‘Order
Details’ screen on the Medizinhub website/ app (‘Platform’) or by calling our
customer care number 9092977199 before it is marked as “Out for Delivery”. Else,
you can refuse it at the time of delivery and a refund will be processed as per the
Refund Policy.</div>
    <div class="refund-helptext">1.2  Diagnostics /Lab Test</div>
    <div class="refund-description">A diagnostic/ lab test can be cancelled anytime unless it is marked ‘Sample
Collected’ by the third-party phlebotomist. Else, you can refuse sample pick up at the
collection location and a refund will be processed after deducting service cost as per
the Refund Policy.
        <ol>
                <li>Product(s) delivered do not match your order.</li>
                <li>Product(s) delivered are past or near to its expiry date (medicines with an
                expiry date of less than 03 months shall be considered as near expiry).</li>
                <li>Product(s) delivered were damaged in transit (do not to accept any product
                which has a tampered seal).</li>
        </ol>
    <div>
    <div class="refund-description">Note: If you receive a damaged product, please refuse to accept the delivery.
However, if you discover damage after opening the package, you can return the item
for a refund. Please be aware that we may not always offer a replacement, as it
depends on product availability. In such cases, a refund will be processed.
In the unlikely event of any issues with your order, we are here to help. You may
submit a return request to our customer service team within 7 (seven) days of
receiving the product. Requests made after this period may be declined.
Once we receive your return/refund request, we will verify its authenticity and ensure
it meets our return guidelines. If your request is valid, we will begin the return and
refund process. Refunds will only be processed after we receive confirmation from
the vendor regarding the product in question.
In cases of baseless or unjustified complaints about product quality or contents, we
reserve the right to take legal action. You will be responsible for any costs we incur in
such instances.
<div class="refund-helptext">Return conditions:</div>
        <ol>
                <li>Products ordered incorrectly are not eligible for return.</li>
                <li>The batch number of the product being returned must match the invoice.</li>
                <li>Returns due to prescription changes are not accepted.</li>
                <li>Products must be in their original manufacturer’s packaging, including price
                tags, labels, barcodes, and the invoice.</li>
                <li>Partially used strips or items cannot be returned. Only fully unopened strips or
                products are eligible.</li>
        </ol>
    </div>
    <div class="refund-title">Return Policy</div>
    <div class="refund-subtitle">1. What is the time period for return of orders</div>
    <div class="refund-helptext">1.1 Medicine Orders</div> 
    <div class="refund-description">We have product specific return policy. The return window ranges from 0-7 days from
the date of delivery. The information regarding the return policy can be found on the
product page. Please check the return policy before placing any order.</div> 
    <div class="refund-helptext">1.2  Healthcare Products</div> 
    <div class="refund-description">All healthcare products have specific return and replacement policy. The
return/replacement window ranges from 0-10 days from the date of delivery. The
information regarding the return policy can be found on the product page. Please
check the return policy before placing any order.
    <span class="refund-description-helptext">[Note- Currently, the Company is not charging any shipping charges for returns from
you.]</span></div>
    <div class="refund-subtitle">2 Return of Products and Cancellation of orders</div>
    <div class="refund-description">
        <ol type="a">
                <li>We strive to deliver correct medicines/items in the right/undamaged condition
every time the customer places an order. We strongly recommend that you check the
condition of the delivered products at the time of delivery and get back to us if there
are any discrepancy.</li>
                <li>If your order is eligible for a return, you can raise a return request within 48
hours from the time of delivery. All returns are reviewed for eligibility and refund is
subject to review and verification by APL team. No return of damaged products is
possible once part or whole of the product has been used.</li>
                <li>To raise the return request and return an item, you can call our help desk at
9092977199 (24*7 customer support), email us at care@medizinhub.com, or contact
our customer support executives through online live chat.</li>
                <li>Items are eligible for a return exclusively under the following circumstances.
                        <ul>
                                <li>Products are delayed beyond 48 hours of the estimated date of
delivery communicated to the customer at the time of placement of the
order.</li>
                                <li>Product(s) delivered do not match the order: This would include items
                                that are different from what the customer ordered.</li>
                                <li>Product(s) were delivered in damaged/non-working condition.</li>
                                <li>Product(s) have missing parts or accessories or different from their
                                description on the product page.</li>
                                <li>Product(s) are returned in original packaging i.e. with labels, barcode,
                                price tags, original serial no. etc.</li>
                                <li>Batch number of the product(s) being returned matches with the one(s)
                                mentioned in the invoice.</li>
                                <li>Product(s)/medicines(s)/bottle(s) are unused. Opened medicine
                                strip(s)/bottle(s) are not eligible for returns.</li>
                                <li>The damages/defects are covered under the manufacturer’s warranty.</li>
                        </ul>
                        <div class="refund-description">Note:Replacement of product(s)/order is not supported as of now. For such cases,
you will need to return the items and refund will be issued post verification. No return
is possible for damaged goods beyond 48 hours of delivery.</div>
                </li>
                <li>Certain categories of products are not eligible for return</li>
        </ol>
        <table class="refund-table">
                <thead>
                   <tr>
                        <th>Categories</th>
                        <th>Type of products</th>
                   </tr>    
                </thead>
                <tbody>
                   <tr>    
                        <td>Temperature controlled medicines</td>
                        <td>Vials, Injections, Pen-fills, Vaccines or other products or specialty medicines
                        cold storage</td>
                   </tr>
                   <tr>    
                        <td>Baby Care</td>
                        <td>Breast Pumps, Diapers, Ear Syringes, Wipe Warmers, Bottle Nipples</td>
                   </tr>
                   <tr>    
                        <td>Food and Nutrition</td>
                        <td>Health supplements and drink</td>
                   </tr>
                   <tr>    
                        <td>Healthcare device</td>
                        <td>Glucometer Lancet, Healthcare Devices, Surgical,Health Monitors</td>
                   </tr>
                   <tr>    
                        <td>Personal Care</td>
                        <td>Oral Care (Toothbrushes, toothpastes, mouthwashes etc); Feminine Hygiene
(Sanitary Pads, Panty Liners, Menstrual Cups etc.); Shaving and Hair
Removal (Men’s Shaving – Razors, Blades, Shaving Foams, Brushes etc.;
Men’s Beard Care – Beard Oil, Beard Serum etc.; Women’s Hair Removal –
Wax Strips, Creams, Razors etc</td>
                   </tr>
                   <tr>    
                        <td>Family Nutrition</td>
                        <td>Infant Baby Food, Toddlers’ and Kids’ Health Drink</td>
                   </tr>
                   <tr>    
                        <td>Vitamin and Mineral Supplements</td>
                        <td>Core Letter Vitamins, Multi-Vitamin</td>
                   </tr>
                   <tr>    
                        <td>Health Care Product</td>
                        <td>Ayurveda Products, Pain Relief Products, Herbal Supplements, Medical
Supplies, Adult Diapers, COVID masks (N95, surgical masks and others if
unpacked)</td>
                   </tr>
                   <tr>    
                        <td>Others</td>
                        <td>Any wearable (COPD vest, bandages, bandage, knee caps) and any item
(solid, gel, aerosol) which may have been partially used</td>
                   </tr>
                </tbody>
        </table>
    </div>
    <div class="refund-subtitle">2 Return of Products and Cancellation of orders</div>
    <div class="refund-description">3.1 Items marked as &quot;Non-Returnable&quot; on the product detail page or items whose
return window has expired cannot be returned. If such an item is indeed returned
along with another returnable item, Medizinhub will disallow a refund or return of the
“Non-Returnable” product to you when our partner licensed retail pharmacy verifies
the returned item(s).</div>
    <div class="refund-subtitle">2 Return of Products and Cancellation of orders</div>
    <div class="refund-description">4.1 You can raise a return request within the time frame mentioned above by
    following these simple steps on the Platform:
        <ol>
                <li>Go to My Orders.</li>
                <li>Select the respective order and click on ‘RETURN’.</li>
                <li>Check to see if the product/s that you wish to return are returnable and have
                an active return window.</li>
                <li>Select the item you wish to return with quantity and reason for return.</li>
        </ol>
     4.2 You can also place a request for return of any product by calling the customer
     support at  90476 60909 .
     4.3 After your return request is processed, we will pick up the return items as per the
     following timelines:
        <ol>
                <li>For Local Cities*: Within 24-48 hours from the time of approval of return
                request.</li>
                <li>For Other Cities: Between 4-5 business days from the time of approval of
return request. Please note that this time period may be longer depending on
the third-party courier partners terms.</li>
        </ol>
        4.4 Please keep the return package ready in its original packaging with all the labels
intact. You are also requested to keep a copy of the invoice/ bill from the seller handy
for verification.
</div>
        <div class="refund-title">Refund Policy</div>
        <div class="refund-subtitle">1. When can I expect the amount to be refunded?</div>
        <div class="refund-description">1.1 Please note that the refund amount mentioned at the time of return on the
Platform is an estimate and will be finalised after completion of verification. Once the
pick-up is completed and the product is verified by the seller, a refund of the total
amount paid for the products returned by you will be initiated for eligible returns as
mentioned above.
        1.2 Refund will be initiated only post successful verification of the products by the
        seller. Please note that the verification process may take:
        <ol>
                <li>For Local Cities*: 48 hours from the time of pick up from your location.</li>
                <li>For Other Cities: 8-10 business days from the date of pick up from your
                location.</li>
        </ol>
        1.3 The amount is expected to reflect in your account after completion of verification
        from the seller as per the following timelines:
        <table class="refund-table">
                <thead>
                   <tr>
                        <th>Method of Payment</th>
                        <th>Refund Timeframe (after successful
verification from third party pharmacy/
vendor)</th>
                   </tr>    
                </thead>
                <tbody>
                   <tr>    
                        <td>Medizinhub wallet and Cash on
Delivery [Note: refunds for cash on delivery orders shall be reflecting in your Medizinhub wallet.]</td>
                        <td>1 business day</td>
                   </tr>
                   <tr>    
                        <td>NEFT</td>
                        <td>1-3 business days</td>
                   </tr>
                   <tr>    
                        <td>Online refund</td>
                        <td>7-10 business days subject to the bank
                        turnaround time and RBI Guidelines.</td>
                   </tr>
                   <tr>    
                        <td>Other Wallets</td>
                        <td>2-3 business days</td>
                   </tr>
                </tbody>
        </table>
        1.4 You understand and acknowledge that we reserve the rights to claim back any
refund that has been processed by us as a result of fraudulent activities such as
return of wrong products or wrong quantity of the products.
</div>
<div class="refund-title">Return policy conditions:</div>
<ol>
        <li>Products ordered by mistake do not qualify for returns.</li>
        <li>The batch number on the product must match the one listed on your invoice.</li>
        <li>Returns due to a change in prescription are not permitted.</li>
        <li>Items must be in their original packaging with intact price tags, labels,
        barcodes, and the original invoice.</li>
        <li>Partially used products or strips are not eligible for return. Only completely
        unopened products or strips will be accepted.</li>
</ol>
</div>