<?php
/** @var \MedizinhubCore\Home\Block\Home $block */
$block = $this->getLayout()->createBlock(\MedizinhubCore\Home\Block\Home::class);
$baseHelper = $this->helper('ET\Base\Helper\Data');
$baseUrl = $this->getBaseUrl();
$todayids = [25, 24];
$accids = [24, 25];
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaBaseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$TodayDeals = $block->getProductCollectionByCategories($todayids);
$MedicalAcc = $block->getProductCollectionByCategories($accids);
?>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
<div class="order-home">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="order-prescription">
                    <div class="row">
                        <div class="col-md-3">
                            <img width="128px" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Prescription_image.png'); ?>" alt="">
                        </div>
                        <div class="col-md-9">
                            <p class="order-prescription-content">
                                Quick order with Prescription
                            </p>
                            <p class="order-offer-prescription">
                                Get 50% OFF and express delivery with prescription
                            </p>
                            <a href="/prescription"><button id="upload-press" type="button" class="book-my-btn customer-register-link grow">Upload Prescription</button></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="order-doctor">
                    <div class="row">
                        <div class="col-md-3">
                            <img src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Prescription_image_2.png'); ?>" alt="">
                        </div>
                        <div class="col-md-9">
                            <p class="order-prescription-content">
                                Quick order with Prescription
                            </p>
                            <p class="order-offer-prescription">
                                Get 50% OFF and express delivery with prescription
                            </p>
                            <a href="/doctor-consult"><button class="book-my-btn grow" type="button">Book My Doctor</button></a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<div style="margin-top:40px;" class="container">
    <div class="row">
        <p style="color: #063851;font-family: Source Sans Pro,Sans-serif;font-size: 24px;font-weight: 600;">Today’s Deals</p>
        <p style="color: #859ca8;font-family: Ubuntu,Sans-serif;font-size: 18px;font-weight: 400;">Get flat 50% discount on top deals <a style="text-decoration:none;float:right;font-weight: 600;color:#00739B !important;font-size: 14px;font-family: Source Sans Pro;" href="/product_list/index/index/id/25/">VIEW ALL</a></p>
        <div class="swiper-container product-slider">
    <div class="swiper-wrapper d-flex">
        <?php if ($TodayDeals && is_iterable($TodayDeals)) : ?>
            <?php foreach ($TodayDeals as $product) : ?>
                <?php
                $productName = $product->getName();
                $productUrl = $product->getProductUrl();
                $productImage = $product->getImage();
                $productImageUrl = $mediaBaseUrl . 'catalog/product' . $productImage;
                $regularPrice = $product->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue();
                $finalPrice = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
                $categoryIds = $product->getCategoryIds();
                $categoryId = reset($categoryIds);
                $category = $objectManager->create('Magento\Catalog\Model\Category')->load($categoryId);
                $categoryName = $category->getName();
                ?>
                <div class="swiper-slide" style="margin-right: 20px;">
                    <div style="background: #f1f9fe; height: 290px !important; border-radius: 8px; padding:10px;" class="product-slide">
                    <a href="<?= $productUrl ?>"><img style="margin:20px 30px;height:105px;" class="grow" width="100px" src="<?= $productImageUrl ?>" alt="<?= $productName ?>"></a>
                        <div class="product-details">
                            <span style="font-size: 18px !important; font-weight: 600 !important; font-family: Source Sans Pro !important; text-decoration:none;" class="product-name">
                                <?= $productName ?><br>
                                <p style="color: var(--Input-Text, #797979); font-family: Source Sans Pro; font-size: 14px; font-style: normal; font-weight: 400; line-height: normal; margin-bottom: 2px;"><?php echo $categoryName; ?></p>
                                <span style="font-family: Source Sans Pro; font-size: 22px; font-style: normal; font-weight: 700; line-height: normal; text-decoration:none;" class="product-price">₹<?= $finalPrice ?></span>
                                <br>
                                <a href="<?= $productUrl ?>"> <button style="margin-top: 5px;width: 176px; height: 44px; padding: 10px 18px; border-radius: 8px; background: linear-gradient(94deg, #03C777 56.99%, #01A462 99.73%); color: #FFF; font-family: Source Sans Pro; font-size: 16px; font-style: normal; font-weight: 700;" class="add-to-cart-btn grow" data-product-id="<?= $product->getId() ?>">Add to Cart</button></a>
                            </span>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php else : ?>
            <p>No deals available today.</p>
        <?php endif; ?>
    </div>
</div>

    </div>
</div>
<div style="margin-top:40px;" class="shop-category">
    <div class="container">
        <div class="row">
            <p style="color: #063851;font-family: Source Sans Pro,Sans-serif;font-size: 24px;font-weight: 600;">Shop Based on Category</p>
            <p style="color: #859ca8;font-family: Ubuntu,Sans-serif;font-size: 18px;font-weight: 400;">We offer a quality product to you </p>
            <div class="row">
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/2/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Mother_and_baby_needs.png'); ?>">Mother & Baby Needs</a> </div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/3/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Health_food.png'); ?>" alt="">Health food & Drinks</a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/4/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Health_care_device.png'); ?>" alt="">Health Care devices </a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/5/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/E_dery_care.png'); ?>" alt="">Elderly Care</a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/6/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Skin.png'); ?>" alt="">Skin Care </a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/7/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Sexual.png'); ?>" alt="">Sexual Wellness</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="margin-top:40px;" class="based-category">
    <div class="container">
        <div class="row">
            <p style="color: #063851;font-family: Source Sans Pro,Sans-serif;font-size: 24px;font-weight: 600;">Shop Medicine Based on Category</p>
            <p style="color: #859ca8;font-family: Ubuntu,Sans-serif;font-size: 18px;font-weight: 400;">We offer a quality product to you</p>
            <div style="margin-top: 20px;" class="row">
                <div class="col-md-2">
                    <div class="scroll-inner"> <a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/8/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/General_Medicine.png'); ?>" alt="">General Medicines </a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"> <a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/9/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Diabetic.png'); ?>" alt="">Diabetics Medicine </a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/10/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Hypertension.png'); ?>" alt="">Hypertension & Cholestrol</a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/11/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/ENt.png'); ?>" alt="">ENT Drugs</a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/12/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Eye.png'); ?>" alt="">Eye Drugs</a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/13/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Oral_drug.png'); ?>" alt="">Oral Drugs</a></div>
                </div>
            </div>
            <div style="margin-top: 20px;" class="row">
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/32/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/joint_pain.png'); ?>" alt="">Joint Pain Drugs</a> </div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/3/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Neu.png'); ?>" alt="">Neurology Medicine </a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/14/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Frame_50.png'); ?>" alt="">Hormonal Drugs </a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/15/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Skinf.png'); ?>" alt="">Periodic Care</a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/16/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Reposiotry.png'); ?>" alt="">Respiratory (Asthma)</a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/17/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Mental.png'); ?>" alt="">Mental Health</a></div>
                </div>
            </div>

        </div>
    </div>
</div>
<div style="margin-top:40px;" class="Health-category">
    <div class="container">
        <div class="row">
            <p style="color: #063851;font-family: Source Sans Pro,Sans-serif;font-size: 24px;font-weight: 600;">Shop on Health Product</p>
            <p style="color: #859ca8;font-family: Ubuntu,Sans-serif;font-size: 18px;font-weight: 400;">Get 5 - 10% offer on health products</p>
            <div class="row">
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/18/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Health_food.png'); ?>" alt="">Health Drinks</a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/19/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Vitsmin.png'); ?>" alt="">Vitamins & Minerals</a> </div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/20/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Ayurvedic.png'); ?>" alt="">Ayurvedic Drinks</a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/21/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Omega.png'); ?>" alt="">Omege & Fish oil</a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/22/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Sports.png'); ?>" alt="">Sports Nutrition</a></div>
                </div>
                <div class="col-md-2">
                    <div class="scroll-inner"><a style="text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;" href="/product_list/index/index/id/23/"><img class="grow" style="padding: 13px;" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Weight.png'); ?>" alt="">Weight Management</a></div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="medical-accessories" style="margin-top:40px;" class="container">
    <div class="row">
        <p style="color: #063851;font-family: Source Sans Pro,Sans-serif;font-size: 24px;font-weight: 600;">Medical Accessories</p>
        <p style="color: #859ca8;font-family: Ubuntu,Sans-serif;font-size: 18px;font-weight: 400;">Get flat 20% discount on medical accessories<a style="text-decoration:none;float:right;font-weight: 600;color:#00739B !important;font-size: 14px;font-family: Source Sans Pro;" href="/product_list/index/index/id/24/">VIEW ALL</a> </p>
       <div class="swiper-container product-slider">
    <div class="swiper-wrapper d-flex">
        <?php if ($MedicalAcc && is_iterable($MedicalAcc)) : ?>
            <?php foreach ($MedicalAcc as $product) : ?>
                <?php
                $productName = $product->getName();
                $productUrl = $product->getProductUrl();
                $productImage = $product->getImage();
                $productImageUrl = $mediaBaseUrl . 'catalog/product' . $productImage;
                $regularPrice = $product->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue();
                $finalPrice = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
                $categoryIds = $product->getCategoryIds();
                $categoryId = reset($categoryIds);
                $category = $objectManager->create('Magento\Catalog\Model\Category')->load($categoryId);
                $categoryName = $category->getName();
                ?>
                <div class="swiper-slide" style="margin-right: 20px;">
                    <div style="background: #f1f9fe; height: 290px !important; border-radius: 8px; padding:10px;" class="product-slide">
                    <a href="<?= $productUrl ?>"><img style="margin:20px 30px;height:105px;" class="grow" width="100px" src="<?= $productImageUrl ?>" alt="<?= $productName ?>"></a>
                        <div class="product-details">
                            <span style="font-size: 18px !important; font-weight: 600 !important; font-family: Source Sans Pro !important; text-decoration:none;" class="product-name">
                                <?= $productName ?><br>
                                <p style="color: var(--Input-Text, #797979); font-family: Source Sans Pro; font-size: 14px; font-style: normal; font-weight: 400; line-height: normal;margin-bottom: 2px;"><?php echo $categoryName; ?></p>
                                <span style="font-family: Source Sans Pro; font-size: 22px; font-style: normal; font-weight: 700; line-height: normal; text-decoration:none;" class="product-price">₹<?= $finalPrice ?></span>
                                <br>
                                <a href="<?= $productUrl ?>"><button class="grow" style="margin-top: 5px;width: 176px; height: 44px; padding: 10px 18px; border-radius: 8px; background: linear-gradient(94deg, #03C777 56.99%, #01A462 99.73%); color: #FFF; font-family: Source Sans Pro; font-size: 16px; font-style: normal; font-weight: 700;" class="add-to-cart-btn" data-product-id="<?= $product->getId() ?>">Add to Cart</button></a>
                            </span>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php else : ?>
            <p>No medical accessories available.</p>
        <?php endif; ?>
    </div>
</div>

    </div>
</div>

<div id="health-devices" style="margin-top:40px;" class="care-device">
    <div class="container">
        <div class="row">
            <p style="color: #063851;font-family: Source Sans Pro,Sans-serif;font-size: 24px;font-weight: 600;">Health Care Devices</p>
            <p style="color: #859ca8;font-family: Ubuntu,Sans-serif;font-size: 18px;font-weight: 400;">Get 10 - 50% offer on health products</p>
            <div class="col-md-2">
                <div class="diabetics-bg">
                    <p style="padding:20px 88px 10px 20px;color: #fff;font-family: Reem Kufi,Sans-serif;font-size: 16px;font-weight: 600;line-height: 24px;">Diabetes Devices <br> 15% OFF </p>
                    <button class="view-health-btn grow" type="button">View All</button>
                </div>
            </div>
            <div class="col-md-2">
                <div class="preganacy-bg">
                    <p style="padding:20px 88px 10px 20px;color: #fff;font-family: Reem Kufi,Sans-serif;font-size: 16px;font-weight: 600;line-height: 24px;">Pregnancy
                        Test Kit <br>
                        15% OFF </p>
                    <button class="preg-view-btn grow" type="button">View All</button>
                </div>
            </div>
            <div class="col-md-2">
                <div class="breathing-bg">
                    <p style="padding:20px 88px 10px 20px;color: #fff;font-family: Reem Kufi,Sans-serif;font-size: 16px;font-weight: 600;line-height: 24px;">Breathing
                        Devices <br>
                        15% OFF </p>
                    <button class="breath-view-btn grow" type="button">View All</button>
                </div>
            </div>
            <div class="col-md-2">
                <div class="fever-bg">
                    <p style="padding:20px 6px 10px 20px;color: #fff;font-family: Reem Kufi,Sans-serif;font-size: 16px;font-weight: 600;line-height: 24px;">Fever Management
                        Device <br>
                        15% OFF </p>
                    <button class="fever-view-btn grow" type="button">View All</button>
                </div>
            </div>
            <div class="col-md-2">
                <div class="body-bg">
                    <p style="padding:20px 73px 10px 20px;color: #fff;font-family: Reem Kufi,Sans-serif;font-size: 16px;font-weight: 600;line-height: 24px;">Body Pain
                        Management
                        15% OFF</p>
                    <button class="body-view-btn grow" type="button">View All</button>
                </div>
            </div>
            <div class="col-md-2">
                <div class="bp-bg">
                    <p style="padding:20px 88px 10px 20px;color: #fff;font-family: Reem Kufi,Sans-serif;font-size: 16px;font-weight: 600;line-height: 24px;">BP <br>
                        Monitors <br>
                        25% OFF</p>
                    <button class="bp-view-btn grow" type="button">View All</button>
                </div>
            </div>
        </div>
    </div>
</div>


<div style="margin-top:40px;" class="combo-category">
    <div class="container">
        <div class="row">
            <p style="color: #063851;font-family: Source Sans Pro,Sans-serif;font-size: 24px;font-weight: 600;">Lab Test Combo Pack</p>
            <p style="color: #859ca8;font-family: Ubuntu,Sans-serif;font-size: 18px;font-weight: 400;">Get 10 - 20% offer on combo pack</p>
            <div style="margin-left: -22px;" class="row">
                <div class="col-md-3">
                    <div class="fullbody">
                        <p style="color: #5a5507;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">
                            Full Body Check up
                            <span>Package</span>
                            <br>
                        </p>

                        <span style="color: #5a5507;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">20% OFF</span> <br>
                        <a href="most-booked-lab"><button class="fullbody-btn grow" type="button">Book Now</button></a>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="diabetics-pack">
                        <p style="color: #934606;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">
                            Diabetes <br>
                            <span>Package</span>
                            <br>
                        </p>
                        <span style="color: #934606;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">20% OFF</span> <br>
                        <a href="most-booked-lab"> <button class="diabetics-btn grow" type="button">Book Now</button></a>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="thyroid-pack">
                        <p style="color: #0A264D;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">
                            Thyroid Test <br>
                            <span>Package</span>
                            <br>
                        </p>
                        <span style="color: #0A264D;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">15% OFF</span> <br>
                        <a href="most-booked-lab"> <button class="thyroid-btn grow" type="button">Book Now</button></a>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="routine-pack">
                        <p style="color: #062B37;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">
                            Routine Test <br>
                            <span>Package</span>
                            <br>
                        </p>
                        <span style="color: #062B37;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">20% OFF</span> <br>
                        <a href="most-booked-lab"> <button class="routine-btn grow" type="button">Book Now</button></a>
                    </div>
                </div>
            </div>
            <div style="margin-top: 20px;margin-left:-22px;" class="row">
                <div class="col-md-3">
                    <div class="womens-pack">
                        <p style="color: #3F0E36;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">
                            Women’s Health <br>
                            <span>Package</span>
                            <br>
                        </p>
                        <span style="color: #3F0E36;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">20% OFF</span> <br>
                        <a href="most-booked-lab"> <button class="women-book-btn grow" type="button">Book Now</button></a>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="mens-pack">
                        <p style="color: #6B0007;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">
                            Men’s Health <br>
                            <span>Package</span>
                            <br>
                        </p>
                        <span style="color: #6B0007;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">20% OFF</span> <br>
                        <a href="most-booked-lab"> <button class="men-book-btn grow" type="button">Book Now</button></a>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="Senior-pack">
                        <p style="color: #2C1254;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">
                            Senior Citizen <br>
                            <span>Package</span>
                            <br>
                        </p>
                        <span style="color: #2C1254;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">15% OFF</span> <br>
                        <a href="most-booked-lab"> <button class="senior-book-btn grow" type="button">Book Now</button></a>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="fever-pack">
                        <p style="color: #054146;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">
                            Fever Test <br>
                            <span>Package</span>
                            <br>
                        </p>
                        <span style="color: #054146;font-family: Reem Kufi,Sans-serif;font-size: 22px;font-weight: 400;line-height: 34px;font-weight:600;">20% OFF</span> <br>
                        <a href="most-booked-lab"> <button class="fever-book-btn grow" type="button">Book Now</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="margin-top:40px;" class="brand-carousel">
    <div class="container">
        <div class="row">
            <p style="color: #063851; font-family: Source Sans Pro, Sans-serif; font-size: 24px; font-weight: 600;">Shop Based on Brands</p>
            <p style="color: #859ca8; font-family: Ubuntu, Sans-serif; font-size: 18px; font-weight: 400;">Buy top brands products with us</p>
            <div class="swiper-containers">
                <div class="swiper-wrapper">
                    <div class="swiper-slide"><img class="grow" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Himalaya.png'); ?>" alt="1"></div>
                    <div class="swiper-slide"><img class="grow" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Dabur.png'); ?>" alt="2"></div>
                    <div class="swiper-slide"><img class="grow" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Vertex.png'); ?>" alt="3"></div>
                    <div class="swiper-slide"><img class="grow" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Cipla.png'); ?>" alt="4"></div>
                    <div class="swiper-slide"><img class="grow" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/P_and_G.png'); ?>" alt="5"></div>
                    <div class="swiper-slide"><img class="grow" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/GSK.png'); ?>" alt="6"></div>
                    <div class="swiper-slide"><img class="grow" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Lilly.png'); ?>" alt="7"></div>
                </div>
                <!-- Add Pagination -->
                <div class="swiper-pagination"></div>
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var mySwiper = new Swiper('.swiper-container', {
            slidesPerView: 6,
            spaceBetween: 20,
            navigation: false,
            loop: true,
            pagination: false,
            autoplay: {
                delay: 2000, // Set the autoplay delay in milliseconds (e.g., 3000 for 3 seconds)
                disableOnInteraction: false, // Set to false if you want autoplay to continue even when the user interacts with the slider
            },
        });
    });
    document.addEventListener('DOMContentLoaded', function() {
        var mySwiper = new Swiper('.swiper-containers', {
            slidesPerView: 7,
            spaceBetween: 20,
            navigation: false,
            loop: true,
            pagination: false,
            autoplay: {
                delay: 2000, // Set the autoplay delay in milliseconds (e.g., 3000 for 3 seconds)
                disableOnInteraction: false, // Set to false if you want autoplay to continue even when the user interacts with the slider
            },
        });
    });
</script>
<style>
    .fullbody {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Lab_Pics1.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
        padding: 26px 0px 27px 20px;
        margin: 0 15px;
    }

    .womens-pack {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Lab_5.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
        padding: 26px 0px 27px 20px;
        margin: 0 15px;
    }

    .mens-pack {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Lab_6.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
        padding: 26px 0px 27px 20px;
        margin: 0 15px;
    }

    .Senior-pack {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Lab_3.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
        padding: 26px 0px 27px 20px;
        margin: 0 15px;
    }

    .fever-pack {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Lab_10.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
        padding: 26px 0px 27px 20px;
        margin: 0 15px;
    }

    .diabetics-pack {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Lab_2.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
        padding: 26px 0px 27px 20px;
        margin: 0 15px;
    }

    .thyroid-pack {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Lab_8.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
        padding: 26px 0px 27px 20px;
        margin: 0 15px;
    }

    .routine-pack {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Lab_4.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
        padding: 26px 0px 27px 20px;
        margin: 0 15px;
    }

    .diabetics-bg {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Bg_pic.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
    }

    .preganacy-bg {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Bg_pic1.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
    }

    .breathing-bg {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Bg_pic3.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
    }

    .fever-bg {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Bg_pic4.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
    }

    .body-bg {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Bg_pic5.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
    }

    .bp-bg {
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Bg_pic6.png'); ?>);
        background-repeat: no-repeat;
        background-size: cover;
        border-radius: 8px;
    }

    .order-prescription {
        background-color: rgba(251, 231, 208, 1);
        padding: 20px;
        border-radius: 8px;
    }

    .routine-btn {
        height: 40px;
        border-radius: 4.347px;
        background: #062B37;
        color: #FFF;
        font-family: Montserrat !important;
        font-size: 14px;
        font-style: normal;
        font-weight: 600;
        width: 107px;
        margin-top: 15px;
    }

    .routine-btn:hover {
        background: #062B37;
        color: #FFF;
    }

    .women-book-btn {
        height: 40px;
        border-radius: 4.347px;
        background: #3F0E36;
        color: #FFF;
        font-family: Montserrat !important;
        font-size: 14px;
        font-style: normal;
        font-weight: 600;
        width: 107px;
        margin-top: 15px;
    }

    .women-book-btn:hover {
        background: #3F0E36;
        color: #FFF;
    }

    .men-book-btn {
        height: 40px;
        border-radius: 4.347px;
        background: #6B0007;
        color: #FFF;
        font-family: Montserrat !important;
        font-size: 14px;
        font-style: normal;
        font-weight: 600;
        width: 107px;
        margin-top: 15px;
    }

    .men-book-btn:hover {
        background: #6B0007;
        color: #FFF;
    }

    .senior-book-btn {
        height: 40px;
        border-radius: 4.347px;
        background: #2C1254;
        color: #FFF;
        font-family: Montserrat !important;
        font-size: 14px;
        font-style: normal;
        font-weight: 600;
        width: 107px;
        margin-top: 15px;
    }

    .senior-book-btn:hover {
        background: #2C1254;
        color: #FFF;
    }

    .fever-book-btn {
        height: 40px;
        border-radius: 4.347px;
        background: #054146;
        color: #FFF;
        font-family: Montserrat !important;
        font-size: 14px;
        font-style: normal;
        font-weight: 600;
        width: 107px;
        margin-top: 15px;
    }

    .fever-book-btn:hover {
        background: #054146;
        color: #FFF;
    }

    .view-health-btn {
        margin-left: 20px;
        margin-bottom: 20px;
        text-shadow: 0px 0px 10px rgba(0, 0, 0, .3);
        color: #e76f51;
        background-color: #fff;
        font-size: 16px;
        border-radius: 8px;
    }

    .preg-view-btn {
        margin-left: 20px;
        margin-bottom: 20px;
        text-shadow: 0px 0px 10px rgba(0, 0, 0, .3);

        color: #F4A261;
        background-color: #fff;
        font-size: 16px;
        border-radius: 8px;
    }

    .breath-view-btn {
        margin-left: 20px;
        margin-bottom: 20px;
        text-shadow: 0px 0px 10px rgba(0, 0, 0, .3);

        color: #E5B84C;
        background-color: #fff;
        font-size: 16px;
        border-radius: 8px;
    }

    .fever-view-btn {
        margin-left: 20px;
        margin-bottom: 20px;
        text-shadow: 0px 0px 10px rgba(0, 0, 0, .3);
        color: #2A9D8F;
        background-color: #fff;
        font-size: 16px;
        border-radius: 8px;
    }

    .body-view-btn {
        margin-left: 20px;
        margin-bottom: 20px;
        text-shadow: 0px 0px 10px rgba(0, 0, 0, .3);
        color: #287271;
        background-color: #fff;
        font-size: 16px;
        border-radius: 8px;
    }

    .bp-view-btn {
        margin-left: 20px;
        margin-bottom: 20px;
        text-shadow: 0px 0px 10px rgba(0, 0, 0, .3);
        color: #e76f51;
        background-color: #fff;
        font-size: 16px;
        border-radius: 8px;
    }

    #link-login {
        font-size: 17px;
        font-weight: 600;
        color: #049B7E;
        font-family: "Source Sans Pro";
        margin-top: 12px;
    }

    .search-btn {
        position: absolute;
        margin-top: -44px;
        margin-left: 532px;
        border-radius: 88px;
        width: 98px;
        height: 41px;
        font-size: 16px;
        background: linear-gradient(94deg, #03C777 56.99%, #01A462 99.73%);
        ;
        color: #fff;
        font-weight: 500;
        border: 1px solid #03C777;
    }


    .diabetics-btn {
        height: 40px;
        border-radius: 4.347px;
        background: #934606;
        color: #FFF;
        font-family: Montserrat !important;
        font-size: 14px;
        font-style: normal;
        font-weight: 600;
        width: 107px;
        margin-top: 15px;
    }

    .diabetics-btn:hover {
        background: #934606;
        color: #FFF;
    }

    .thyroid-btn {
        height: 40px;
        border-radius: 4.347px;
        background: #0A264D;
        color: #FFF;
        font-family: Montserrat !important;
        font-size: 14px;
        font-style: normal;
        font-weight: 600;
        width: 107px;
        margin-top: 15px;
    }

    .thyroid-btn:hover {
        background: #0A264D;
        color: #FFF;
    }

    .grow {

        cursor: pointer;
        transition: all 0.3s ease-in-out;
    }

    .grow:hover {
        transform: scale(1.1);
    }

    .fullbody-btn {
        height: 40px;
        border-radius: 4.347px;
        background: #5A5507;
        color: #FFF;
        font-family: Montserrat !important;
        font-size: 14px;
        font-style: normal;
        font-weight: 600;
        width: 107px;
        margin-top: 15px;
    }

    .fullbody-btn:hover {
        background: #5A5507;
        color: #FFF;
    }

    .home-index-index #maincontent {
        display: none !important;
    }

    footer {
        display: flex !important;
        background: #049B7E !important;
    }

    .scroll-inner {
        width: 100%;
        text-align: center;
    }

    .order-doctor {
        background-color: rgba(204, 255, 240, 1);
        padding: 20px;
        border-radius: 8px;
    }

    .order-prescription-content {
        color: #003827;
        font-family: Source Sans Pro, Sans-serif;
        font-size: 24px;
        font-weight: 600;
    }

    .order-offer-prescription {
        color: #5b95c1;
        font-family: Source Sans Pro, Sans-serif;
        font-size: 16px;
        font-weight: 400;
        margin-top: -10px;
    }

    .book-my-btn {
        background-color: #03c777;
        border-radius: 8px;
        font-size: 16px;
        font-weight: 600;
        color: #fff;
        height: 44px;
    }

    .book-my-btn:hover {
        background-color: #03c777;
        color: #fff;
    }
</style>
