<?php
$baseUrl = $this->getBaseUrl();
?>
<div class="fees-content">
    <div class="breadcrumbs" ><a href="<?php echo $baseUrl; ?>">Home</a> <Span class="breadcrumb-name">> Fees & Payments Policy</span></div>   
    <h1 class="fees-title">MedizinHub Fees and Payment Policy</h1>
    <p class="fees-description">Welcome to www.medizinhub.com (&quot;medizinhub.com&quot;, &quot;medizinhub, &quot;Website&quot;,
&quot;Pharmacy&quot;, or &quot;we&quot;). This Website/App is managed and operated by Teanso
Technologies private Limited whose registered office is in Chennai, Tamil Nadu,
India. <br>Teanso Technologies Private Limited a company incorporated under the Companies
Act, 2013 (18 of 2013) with its registered office at 3a/5 , Balakrishnan Street, Senthil
Nagar (South Extn), Chromepet, Chennai - 600 044, Tamil Nadu, India. (“Teanso”,
“we”, “us” or “our”), manages and operates www.medizinhub.com and its
corresponding mobile application under the brand name medizinhub (collectively
referred to as the “ Website”) where you can place orders to purchase the Products
and/or Services listed/available on the Website offered by us to the users of the
Website (“User” or “Users” or “you”).</p>
<h2 class="fees-title">FEES AND PAYMENTS POLICY</h2>
<p class="fees-description">This Fees and Payments Policy (“FPP Policy”), together with the Terms and
Conditions [accessible at <a href="#">https://www.medizinhub.com/terms-and-conditions</a>]
describes Teanso’s accepted payment methods, and Teanso’s policies and
procedures in relation to acceptance of fees and payments towards the services
offered through the Website. Teanso’s primary object is to ensure that the Website is
user friendly and equipped with reasonably expected security infrastructure to
protect any financial information which may be shared by User. <br>User(s) are required to peruse and understand the terms of this FPP Policy. If you do
not agree to the terms contained in this FPP Policy, you are advised not to accept
the Terms of Use and this FPP Policy and may forthwith leave and stop using the
Website. The terms contained in this FPP Policy shall be accepted without
modification and also, by using, browsing, accessing, or purchasing on the Website,
you agree to be bound by the terms contained herein.</p>
<h2 class="fees-title">FEES AND PAYMENT METHODS</h2>
<p class="fees-description">
    <ol>
        <li><strong>Browsing Fees: </strong>Currently, Teanso does not charge any fees for browsing the
website. However, Teanso may introduce fees in the future, either for
accessing the website or using specific features. Should this occur, you agree
to pay the applicable fees. Teanso is not obligated to provide prior notice
before implementing such charges, and your continued use of the website will
imply acceptance of these changes.</li>
        <li><strong>Payment Methods: </strong>For user convenience, Teanso offers several payment
methods. Without prior notice, Teanso reserves the right to add or remove any
of the following options:
        <ol type="A">
            <li>Net banking services</li>
            <li>Select credit cards</li>
            <li>Select debit cards</li>
            <li>Cash on delivery</li>
            <li>Prepaid payment instruments and electronic wallets</li>
            <li>Any other payment method Teanso introduces in the future</li>
        </ol>
These methods are collectively referred to as &quot;Payment Options.&quot; Although
Teanso endeavors to offer a range of payment options, it currently only
accepts payments from major selected banks. Payments made with
international debit or credit cards are not accepted.</li>
        <li><strong>Payment Acceptance: </strong>Teanso retains full discretion regarding the
acceptance of any payment via the available Payment Options. It reserves the
right to reject payments for any reason. To validate transactions, Teanso may
request a copy of your photo ID (e.g., PAN card). Failure to provide this may
result in the rejection of your payment.</li>
<h2 class="fees-title">PAYMENT TERMS AND CONDITIONS</h2>
<li><strong>Providing Financial Information: </strong>When using payment options, the user
agrees to provide accurate financial details, such as credit/debit card
information or prepaid account details, which may be stored by Teanso’s third-
party payment gateway provider. Users should only use cards or accounts
they legally own or are authorized to use. The user is solely responsible for
the security and confidentiality of their financial details. Teanso disclaims any
responsibility for unauthorized use of a user&#39;s financial information or identity.</li>
<li><strong>Teanso’s Responsibility: </strong>Teanso is not liable for any loss or damage a user
might face due to:
        <ol type="A">
            <li>Lack of authorization for transactions, including those done using gift
            cards or vouchers from Teanso promotions.</li>
            <li>Exceeding credit or debit limits set by the user&#39;s bank.</li>
            <li>Select debit cards</li>
            <li>Cash on delivery</li>
            <li>Payment issues caused by technical glitches during transactions.</li>
            <li>Transactions being declined for reasons outside Teanso’s control.</li>
        </ol>
</li>
<li><strong>Transaction Limits and Rejections: </strong>Teanso reserves the right to limit the
number of transactions a user can perform on the website. If a user exceeds
these limits, Teanso may refuse to process their transactions. Teanso also has the right to reject transactions from users with questionable transaction
histories. In cases of suspicious transactions, Teanso may delay or cancel
orders, and will not be liable for any claims resulting from these decisions.</li>
<li><strong>Product Pricing and Taxes: </strong>All products listed on the platform include
applicable taxes. Users are responsible for paying any additional fees or taxes
on their purchases, including VAT, GST, and other duties. If there is a pricing
error on the website, the following will apply:
    <ol type="A">
        <li>If the product’s maximum retail price (MRP) is lower than the price on
the website, users can report the issue within two days, and upon
confirmation, Teanso will refund the difference.</li>
        <li>If the MRP is higher than the website price and no discount applies,
Teanso may hold the product until the price discrepancy is resolved.
Users may choose to pay the difference or cancel the purchase.</li>
        <li>For refunds, users must email Teanso with bank details. Refunds for
        cash-on-delivery orders will be processed through net banking.</li>
    </ol>
</li>
<li><strong>Payment Terms: </strong>In addition to Teanso’s payment policies, users must comply
with the terms of their bank or financial institution. If a bank declines a
transaction, Teanso is not liable.</li>
<li><strong>Third-Party Payment Providers: </strong>Teanso may partner with third-party
payment providers, including banks, under Indian law.</li>
<li><strong>Unauthorized Purchases: </strong>If users notice an unauthorized charge for a
purchase, they should first check if someone they know made the transaction.
If not, they must report it to Teanso within two days for investigation.</li>
<li><strong>Invalidated Payments: </strong>If a user’s payment is invalidated, Teanso reserves
the right to retrieve the payment from the user&#39;s wallet. If there are insufficient
funds, users must remit the payment within two to four working days. Failure
to do so may result in legal action.</li>
<li><strong>Cash on Delivery (COD): </strong>Users can pay in cash upon delivery for orders up
to INR 10,000. However, Teanso may limit the availability of COD for certain
products or locations. Users must also review the Return, Refund, and
Cancellation Policy for terms related to COD payments.</li>
</ol>
</p>
<h2 class="fees-title">Customer Support Team:</h2>
<p class="fees-description">You may direct any queries or concerns relating to the Fees and Payment policy to
our customer support team who can be contacted at:</p>
<h2 class="fees-title">Contact Details:</h2>
<p class="fees-description">E- mail id – <a href=""> contact@medizinhub.com </a></p>
<p class="fees-description">Contact No - 90476-60909</a></p>
</div>