<?php
$baseUrl = $this->getBaseUrl();
?>
<div class="terms-and-conditions-content">
<div class="breadcrumbs"><a href="<?php echo $baseUrl; ?>">Home</a>><Span class="breadcrumb-name">> Terms & Conditions</span></div>    
<h1 class="terma-and-condition-title">Medizinhub Terms and Conditions</h1>
<h2 class="terms-title">Terms of use</h2>
<p class="terms-description">Please read these terms of use carefully by accessing or using this internet based
platform, you agree to be bound by the terms described herein and all terms
incorporated by reference. If you do not agree to all of these terms, do not use this
internet based platform.</p>
<h2 class="terms-title">1. GENERAL</h2>
<p class="terms-description"><span><a href="#">www.medizinhub.com</a></span> an internet-based portal and “medizinhub”, a mobile
application, (hereinafter together be referred to as “Website&quot;) is run, operated and
maintained by Teanso Technologies Private Limited (hereinafter to be referred as
“Company” or “We” or “Our” or “Us”), a company incorporated under the Companies
Act, 2013 (18 of 2013) with its registered office at 3a/5 , Balakrishnan Street, Senthil
Nagar (South Extn), Chromepet, Chennai - 600 044, Tamil Nadu, India; website -
www.teanso.com.<br>For the purpose of these Terms, wherever the context so requires &quot;You&quot;, “Your” or
&quot;User&quot; shall mean any natural or legal person who accesses, uses or subscribes to
our Website, agrees to become a buyer on the Website or avails or offers to avail
any of our services.<br>Use of the Website is offered to You, subject to acceptance of all the terms,
conditions and notices contained in these Terms including applicable policies which
are incorporated herein by reference, along with any amendments / modifications
made time to time by Company at its sole discretion and posted on the Website,
including by way of imposing an additional charge for access to or use of a
service(s).<br>The Company reserves the right to change or modify these Terms or any policy or
guideline of the Website including the Privacy Policy, at any time and in its sole
discretion. Any changes or modifications will be effective immediately upon posting
the revisions on the Website and You waive any right You may have to receive
specific notice of such changes or modifications, provided however that, We will
inform You of such changes within such timelines as may be specified under the
applicable laws. Your continued use of the Website will confirm Your acceptance of
such changes or modifications; therefore, You should frequently review these Terms
and applicable policies to understand the terms and conditions that apply to Your use
of the Website.<br>By (i) using this Website or any facility or service provided by this Website in any
way; or (ii) merely by browsing the Website, You agree that You have read,
understood and agreed to be bound, including without limitation, by these Terms, the
Website’s Privacy Policy and such other rules, guidelines, policies, terms and
conditions as are relevant under the applicable law(s) in India and other jurisdictions,
for the purposes of accessing, browsing or transacting on the Website, or availing
any of the Services, and such rules, guidelines, policies, terms and conditions shall
be deemed to be incorporated into, and considered as part and parcel of these
Terms.<br>Our Website is operated, and services are provided in compliance with the laws in
India and Company shall not be liable to deliver any Products or provide any
Services purchased by You in locations outside India. If you access our services
from locations outside India, you do so at your own risk and you are solely liable for
compliance with applicable local laws. The User agrees to use the service to
authorise an individual and get the products from the third party on his/her behalf.
Where you use any third-party website or the products or services of any third party,
You may be subject to alternative or additional terms and conditions of use and
privacy policies.</p>
<h2 class="terms-title">2. PRODUCTS AND SERVICES</h2>
<p class="terms-description">The Website is a platform that facilitates, as an intermediary, the online requisition by
the User for purchase of medicines and wellness / health related products and
services offered by Company&#39;s various registered third-party/ies (third parties shall
for the purpose of this Terms, include without limitation, third party retail pharmacies,
third-party labs et al) (&quot;Products and Services&quot;). The sale &amp; purchase / transaction
between the registered third parties and You, of Products and Services, facilitated by
the requisition placed by You on the Website shall be governed by these Terms.
Company is not and cannot be a party to or save as except as may be provided in
these Terms, control in any manner, any transaction between You and the third
parties.</p>
<h2 class="terms-help-title">Technology Platform for Pharmaceutical Products –</h2>
<p class="terms-description">The Website facilitates the purchase of drugs and other pharmaceutical products,
nutraceutical products and services (which shall also include Over the Counter
(OTC) and wellness products) offered by third-party retail pharmacies (“Retail
Pharmacies”). The Company and the Website merely provide hosting and
technology intermediary services to You and persons browsing/ visiting the Website.
All items offered for sale on the Website, and content (including product descriptions,
images and the like) made available by the Retail Pharmacies, are third party
content and describe third-party products and services. The Company has no control
over such third-party user generated content, Products or Services and does not
originate or initiate the transmission, or select the sender/recipient of the
transmission, or the information contained in such transmission. The authenticity,
accuracy or genuineness of the Products and Services made available by the Retail
Pharmacies through the Website shall be the sole responsibility of the Retail
Pharmacies. The Company shall have no liability with respect to the authenticity of
the Products and Services being facilitated through the Website. The Company does
not take any representation or warranty as to legal title of the Products and Services
offered for sale by the Retail Pharmacies on the Website. The right, title, claim or
interest in the products sold through the Website shall not vest with the Company
and the Company shall not have any obligations or liabilities in respect of any
transactions on the Website.<br>The Company is not responsible for delayed performance, non-performance or
breach of contract entered into between You and the third-party for purchase and
sale of goods or services offered by such Retail Pharmacies on the Website; The
Company gives no guarantee that the concerned Retail Pharmacies will perform any
transaction concluded on the Website. The Company is not responsible for the
Products and Services which are out of stock, back ordered or otherwise
unavailable, but were shown as available on the Website at the time of placement of
order by You. Content: You agree and acknowledge that the respective Retail
Pharmacies are exhibiting third party content which includes catalogue of drugs/
pharmaceutical products or services, and information in relation to such drugs/
pharmaceutical products or services, on the Website. The content available on the
Website, including without limitation, text, copy, audio, video graphics etc is for
general information purposes only and does not constitute either an advertisement or
promotion of any drug being offered for sale by the Retail Pharmacies on the
Website or any professional medical advice, diagnosis, treatment or
recommendation of any kind. Further, the Company shall not be responsible for
ensuring that the content made available are not misleading and describe the actual
condition of the Products and Services. Also, You acknowledge and understand that
the Company provides no warranty or representation with respect to the authenticity
or accuracy of the information provided on the Website and You must do Your own
check. The ranking of goods and services as provided on the Platform are
determined after collection of rating and feedback from the User, and the Company
shall not be in any manner held responsible for accuracy of the same. If Retail
Pharmacies or Users find any wrong information on the Website in relation to such
Retail Pharmacy, Products or Services, they may contact the Company immediately
for such corrections. The Company shall not be, in any event, held responsible or
liable for any damages arising out of such content by third parties.</p>
<h2 class="terms-help-title">Prescription Drugs:</h2>
<p class="terms-description">In order to purchase drugs and pharmaceutical products that require a valid
prescription, You are required to upload a scanned copy of the valid prescription on
the Website. By submitting a prescription on the Website, you hereby grant consent
to process your personal and health information contained in the prescription for the
purpose of fulfilling your order and for such other purposes as mentioned in the
Terms and Privacy Policy. If you are submitting a prescription on behalf of another
individual, you warrant that you have the necessary authority to contract with the
Website on behalf of the other individual and provide such information and consent
on behalf of such other individual. You acknowledge that the invoice for the Products
will be issued in the name of the person listed on the prescription. The Retail acies,
with respect to any drugs or pharmaceutical products, may dispense only those
quantities as are specified in the prescription. Retail Pharmacies will verify the
prescription forwarded by You and in case of any discrepancy observed by the Retail
Pharmacies, the order may be cancelled by the Retail Pharmacies. The delivery of
your order is not in the Company’s control and the Company shall not be responsible
for any delay.</p>
<h2 class="terms-help-title">Suggestion Of Alternate Of Prescribed Drugs:</h2>
<p class="terms-description">You acknowledge and accept that as per the extent applicable laws within the
territory of India the order for an alternate prescription drug would only be processed
if: (i) a registered medical practitioner has permitted /approved/provided consent for
any such other equivalent generic drug containing similar or substantially similar
composition as the prescribed drug, to be dispensed in place of the prescription
drug; (ii) or if the prescription lists the active pharma ingredient/salt names instead of
a specific brand name, in which case also, dispensation of such drug shall be
certified and approved by a registered medical practitioner, and (iii) You shall have
provided Your consent in respect of such substitution of the prescribed drug.
In the event of an invalid prescription or unavailability of the prescription drug, (i) You
may avail online tele-consultancy with registered medical practitioners through our
partner platform Docstat, wherein the registered medical practitioner shall prescribe
an alternate by replacing the original prescription; or (ii) a third party registered
pharmacist shall place a call on Your registered mobile number, whereby an
alternate drug is suggested, and after such alternate drug being confirmed and
vetted by third party registered medical practitioners associated with the Platform
(through Docstat) by way of a validated prescription, and thereafter dispensed
accordingly. A prescription for such alternate drug may be made available to You at
Your request. Any and all alternate prescription drugs are dispensed only on
receiving consent from You. All online and tele-consultation provided by the third-
party registered medical practitioner shall be through a secured recorded line. You
further agree and acknowledge that any exchange (including but not limited to e-
prescriptions) between the third party registered medical practitioners, pharmacists
and You over telephone shall be recorded and preserved in the database of the
Company for quality, assurance, monitoring, verification of compliance with
applicable laws and value addition purposes; and the Company, the Platform, the
third party registered medical practitioners and pharmacists shall have access to the
same. All such exchange of information shall be utilised and processed strictly in
accordance with the Privacy Policy made available on the Platform.</p>
<h2 class="terms-help-title">Invitation to offer for sale:</h2>
<p class="terms-description">The listing of drugs and other pharmaceutical products on the Website by the Retail
Pharmacies is merely an ‘invitation to an offer for sale’ and not an ‘offer for sale’. The
placement of an order by You shall constitute an offer by You to enter into an
agreement with the Retail Pharmacies (“Offer”). The acceptance of the Offer would
only be undertaken by the Retail Pharmacy(s) after the validation/ verification of the
prescription by such Retail Pharmacy (in case of Prescription Drugs) and the
ascertainment of the available stock in the relevant Retail Pharmacy(s) (in the case
of prescription as well as other drugs/ pharmaceutical products). In the event your
Offer is not accepted by the Retailer, the Company will communicate the same to
you through SMS, e-mail or phone call. It is hereby clarified that any reference of the
term ‘offer/ offered for sale by the Retail Pharmacy(s), as appearing in these Terms,
shall be construed solely as an ‘invitation to offer for sale’ by any such Retail
Pharmacy(s).</p>
<h2 class="terms-help-title">Invitation to offer for sale:</h2>
<p class="terms-description">The listing of drugs and other pharmaceutical products on the Website by the Retail
Pharmacies is merely an ‘invitation to an offer for sale’ and not an ‘offer for sale’. The
placement of an order by You shall constitute an offer by You to enter into an
agreement with the Retail Pharmacies (“Offer”). The acceptance of the Offer would
only be undertaken by the Retail Pharmacy(s) after the validation/ verification of the
prescription by such Retail Pharmacy (in case of Prescription Drugs) and the
ascertainment of the available stock in the relevant Retail Pharmacy(s) (in the case
of prescription as well as other drugs/ pharmaceutical products). In the event your
Offer is not accepted by the Retailer, the Company will communicate the same to
you through SMS, e-mail or phone call. It is hereby clarified that any reference of the
term ‘offer/ offered for sale by the Retail Pharmacy(s), as appearing in these Terms,
shall be construed solely as an ‘invitation to offer for sale’ by any such Retail
Pharmacy(s).</p>
<h2 class="terms-help-title">Transfer of Property and Completion of Sale:</h2>
<p class="terms-description">Upon acceptance of the Offer by the concerned Retail Pharmacies (being the brick-
and-mortar pharmacy), the Products and Services would be dispensed at the
pharmacy, in accordance with the terms of the order placed by You. Such
dispensation shall also take place under the direct/ personal supervision of the
pharmacist of the Retail Pharmacy, wherever required under the applicable law(s).
You agree and acknowledge that the property and title in the Products and Services
ordered by You shall stand immediately transferred to You upon the dispensation of
Products and Services and the raising of the invoice at the concerned Retail
Pharmacies. Accordingly, the sale of Products and Services is concluded at the
concerned Retail Pharmacy itself. The invoice in relation to the Products and
Services, that are required to be delivered to You shall be issued by the concerned
Retail Pharmacy (being the brick-and-mortar pharmacy) which is to process and
satisfy the order for such Products and Services.</p>
<h2 class="terms-help-title">Drugs Delivery:</h2>
<p class="terms-description">The Products and Services shall be delivered by the Retail Pharmacies or
independent contractors. You accept and acknowledge that the courier/ delivery
personnel, engaged by the Retail Pharmacies or the Company, shall be Your Agent
for the delivery of the Products and Services from the concerned Retail Pharmacies
to the address notified by You, with no control over the Products and Services and
no additional obligation apart from standard delivery obligations and duty of care.
You further agree and acknowledge that such courier/ delivery personnel acts as
Your agent for collecting the medicines from the Retail Pharmacy. The services are
being undertaken by Your Agent with Your consent and therefore the Company is
merely facilitating this, and will have no liability or responsibility in this regard.</p>,
<h2 class="terms-help-title">Diagnostics Services:</h2>
<p class="terms-description">The Company as a marketplace facilitates Users to avail diagnostic test/ package
facilities offered by third-party operated labs (“Labs”) through (i) the third party’s tab
or (ii) the medizinhub Labs’ tab on its Website. Labs are responsible for providing
services (including allied services such as sample collection, conducting tests,
generating reports, etc) to the Users in regards to the diagnostic test/ package
facilities availed by them through the Website. Further, the Company shall in no
event be responsible for services (including allied services such as the sample
collection, conducting tests, generating reports etc) provided. The Company only
provides facilitation services to the Users of the Website. User and the Labs agree to
use of the Website and the materials provided therein only for purposes that are
permitted by: (a) these Terms; and (b) any applicable law(s), regulation or generally
accepted practices or guidelines in the relevant jurisdictions.
Notwithstanding anything to the contrary contained herein, Labs alone shall be liable
for Labs’ dealings and interaction with the Users who avail the services of the Labs
or diagnostic centres contacted or managed through the Website and the Company
shall have no liability or responsibility in this regard. The Company does not
guarantee or make any representation with respect to the correctness, completeness
or accuracy of the information or details provided by such User, Labs or any
diagnostic centre or any third party through the Website. The Company may, at its
sole discretion, suspend Labs’ or Users’ ability to use or access the Website at any
time while the Company investigates complaints or alleged violations of these Terms,
or for any other reason. The Company has the right to edit profiles of Labs to make
them more suitable for package searches on the Website. If Labs and/ or Users find
any wrong information on the Website in relation to such Labs and/or User, they may
contact the Company immediately for such corrections. The Company shall have no
liability or responsibility in this regard.</p>
<h2 class="terms-help-title">Online Doctor Consultancy:</h2>
<p class="terms-description">The Company facilitates provision of healthcare products and services to the Users.
The words “Your Physician” or “Your Doctor” or “Healthcare Provider” or similar
words on the Website, shall mean any registered medical practitioner (RMPs) with
whom the User has a doctor-patient relationship. Any consultation services availed
through the Website are fulfilled by third party RMPs made available through third
party service provider Docstat. These third party RMPs are not related to the
Company but merely provide their services to You with Your consent. The Company
hereby explicitly states that it does not provide any kind of telemedical consultation
to its Users/You. You acknowledge that the content, text, data, graphics, images,
information, suggestions, guidance, blogs, information and other materials that is
provided to You on the Website should be used for information purposes only and do
not constitute medical advice and should not be relied upon as a substitute for sound
professional medical advice, evaluation or care from a doctor except for any advice,
information or direction obtained by You directly from Your Doctor. You agree and
acknowledge that the third party RMPs (as available through third party service
providers) are independent contractors, whose services are being availed by You
upon Your implied/ explicit consent and hence, the Company, in no event, shall be
directly or vicariously liable for any advice, medical consultancy or any other loss
arising pursuant to Your engagement with such third party RMPs. Your reliance on
such third party RMPs is solely Your responsibility and at Your sole discretion, and
the Company assumes no responsibility and/or liability in relation to Your
consultation/communication with such third party RMPs, including but not limited to
the quality of services offered by such third party RMPs, which shall at all times be at
Your sole risk and responsibility. In the event of any non-compliance or malpractice
by any such third party RMPs, You affirm that You will bring to our immediate
attention, any such incidence, for us to take necessary actions required under
applicable laws and raise it with the third-party service providers. Further, You affirm
that You shall not take any action against the Company for any acts (or omission) of
the RMPs.<br>You agree and acknowledge that any e-prescription issued pursuant to any online
consultancy service as availed by You, shall be issued by Your Doctor and in
compliance with applicable laws of India. Where such prescription is not constituted
as a valid prescription, the same would not be used for dispensation of medicines by
any pharmacist including the Retail Pharmacies. We only act as an intermediary; and
in the event You request Us to enable the processing of the e-prescription or any
form thereof (whether original or scanned copy of the original prescription) and We
assume no responsibility and/ or liability in relation to the dispensation of the
medicines, which shall at all times be at Your sole risk and the sole responsibility of
the Retail Pharmacies supplying the medicines to You. Reliance on any information
provided on the Website is solely at Your own risk. You should follow the advice of
Your Doctor at all times. The services are not for use in medical emergencies or for
critical health situations and may not be the best solution where a face-to-face
consultation is required. Your sole discretion shall apply in such cases. In case of
any medical emergency, You should call Your nearest doctor/hospital or any related
helpline and seek immediate medical assistance without any delay and should under
no circumstances, delay seeking advice from Your nearest doctor/hospital on
account of something that You may have heard/viewed on the Website.
Further, it is Your responsibility for ensuring that the information submitted is
accurate and the Company shall not make any effort to validate any information
provided by You for using the services. The opinions, statements, consultation via
digital mode provided by the third party RMPs shall not reflect the opinions of the
Company, its affiliates etc. The Company makes no warranty that the services will
meet Your requirements, or that the service(s) will be uninterrupted, timely, secure,
or error free. This includes loss of data, or any service interruption caused by the
Company employees. The Company is not responsible for transmission errors and
corruption of data.</p>
<h2 class="terms-help-title">Patient Support Program (PSP or Program):</h2>
<p class="terms-description">The Company provides services through the Platform and facilitates the Users to
avail personalized health condition or disease management support (“Program”)
through the third-party experts associated with us including registered medical
practitioners, nutritionists or any other specialists or professionals (“Professionals”).
The Program is designed with the objective of providing holistic health condition or
disease management support to the Users through the Professionals which shall
help the Users in enhancing their well-being. The Program may include with certain

limitations diagnostics tests, counselling sessions, teleconsultations with third-party
RMPs, and other health coaches such as nutritionists, psychologists, fitness coaches
amongst others. All educational content that is being created with the clinical
oversight of the Professionals and experts empanelled with us (collectively referred
to as “Medical Experts”). The opinions, statements, answers, and tele-consultations
(collectively referred to as “Consultation”) provided by the Professionals through the
Platform are solely the individual and independent opinions and statements of such
Professionals or Medical Experts and do not reflect the opinions of the Company or
its affiliates.<br>The company may connect You with Professionals who may be suitable to deliver
the health care that You are seeking based on information that You provide to us.
However, the Company in no event recommends or endorses any specific tests,
physicians, products, procedures, opinions, or other information that may be
provided by the Professional and the Company bears no responsibility or liability for
the correctness and genuineness of any such advice provided by the Professional,
and the Professional shall solely be responsible and liable for the same.
The Services should not be treated as a replacement for obtaining consultation for
diseases as the consultation provided through the Platform are provided on ‘as is’ or
‘as available’ basis for guidance purposes only, without any warranties,
representations, and conditions. Therefore, You are free to confirm the advice
rendered through this service on the Platform with Your Doctor. The Consultations
provided through the Platform are not diagnostic in nature and are merely being
offered to support User’s management of an existing health condition. The
exchanges between the Professionals and the User may occur vide any mode
including a chat window, telephonically or via SMS or email (as the case maybe),
and such records may be accessed by the Company for quality control and support
related purposes and are dealt with in accordance with the terms of the Privacy
Policy. Further, the purpose of maintaining such records and Your consent regarding
the retention of such data will be recorded before You sign up for the Program, and
the information provided by You or the information generated as a result of the
Program shall be stored, used, and secured as per the terms provided in the
Company’s Privacy Policy. In case You choose to not provide Your consent to
recording Your calls, or chat content that may have personal information required for
the Program purposes, the Company reserves the right to not facilitate the Services
for which such personal information is sought. Please see our Privacy Policy page,
for more information on storage, use, and protection of sensitive data and personal
information that may be included in prescriptions, or consultations.</p>
<h2 class="terms-title">3. ELIGIBILITY OF USE</h2>
<p class="terms-description">Use of the Website is available only to persons who can form legally binding
contracts under Indian Contract Act, 1872. Persons who are &quot;incompetent to
contract&quot; within the meaning of the Indian Contract Act, 1872 including without
limitation, minors, un-discharged insolvents etc. are not eligible to use the Website.
The Products shall also not be available to any Users suspended or removed from
the Company’s system for any reason whatsoever. If You do not conform to the
above qualification, You will not be permitted to put a requisition for the Products
through the Website. By accessing and using this Website, You represent that You
are of legal age to form a binding contract and are not a person barred from entering
into a contract under the laws as applicable in India. Notwithstanding the foregoing, if
You are below the age of eighteen (18) years, You may avail the services provided
by the Website, through Your legal guardian in accordance with the applicable laws.
Company reserves the right to terminate your membership and / or refuse to provide
You with access to the Website if it is brought to Company’s notice or if it is
discovered that You are under the age of 18 years. Company reserves the right to
refuse access to use the services offered at the Website to new Users or to
terminate access granted to existing Users at any time without according any
reasons for doing so and You shall have no right to object to the same.
You shall not have more than one active Account on the Website. Additionally, You
are prohibited from selling, trading, or otherwise transferring Your Account to another
party.</p>
<h2 class="terms-title">4. USER ACCOUNT, PASSWORD AND SECURITY</h2>
<p class="terms-description">Company shall enable You to make the requisition of Products and Services
available to You through the Website, only if You have provided Company certain
required User information, including without limitation, name; user ID; email address;
address; gender; age; phone number; password; valid finance account information;
and other details and created an account (&quot;Account&quot;) through Company ID and
password or other log-in ID and password, which can include a facebook, gmail,
yahoo ID or any other valid email ID (collectively, the &quot;Account Information&quot;). The
transaction and delivery of the Products by the registered merchants/vendors may
also be subject to procedures for use of the Website, Terms, uploaded guidelines,
rules, additional terms of service, or other disclaimer &amp; notices, if any (&quot;Additional
Terms&quot;). If there is any conflict between the Terms and the Additional Terms, the
Additional Terms shall take precedence in relation to that service. The Website
requires You to register as a User by creating an Account in order to avail the
services provided by the Website. You will be responsible for maintaining the
confidentiality of the Account Information and are fully responsible for all activities
that occur under Your Account. You agree to (a) immediately notify Company of any
unauthorized use of Your Account or Account Information or any other breach of
security, non-compliance with the Telemedicine Practice Guidelines dated March 25,
2020, or any other applicable laws, rules, regulations and guidelines as may be
notified from time to time and (b) ensure that You exit / log out from Your Account at
the end of each session. Company cannot and will not be liable for any loss or
damage arising from Your failure to comply with this Paragraph 4. You may be held
liable for losses incurred by Company or any other User of or visitor to the Website
due to authorized or unauthorized use of Your Account as a result of Your failure in
keeping Your Account Information secure and confidential or otherwise. The Website
also allows / shall allow restricted access to the Website for unregistered Users. You
shall ensure that the Account Information provided by You in the Website&#39;s
registration form is true, complete, accurate and up to date. Use of another User&#39;s
Account Information for availing the services offered by Company is expressly
prohibited. If You provide any information that is untrue, inaccurate, not current or
incomplete (or becomes untrue, inaccurate, not current or incomplete), or Company
has reasonable grounds to suspect that such information is untrue, inaccurate, not
current or incomplete, Company has the right to suspend or terminate Your Account
and refuse any and all current or future use of the Website by You. You confirm that
you are the authorised holder of the credit card, any payment instrument, or the
original Account holder used in the transactions he/she makes using the Website.
Company will not be responsible for any financial loss, inconvenience or mental
agony resulting from misuse of the Your ID/password/credit card number/Account
details for using the Website. The Website uses temporary cookies to store certain
data (that is not sensitive personal data or information) that is used by Company for
the technical administration of the Website, research and development, and for User
administration. In the course of serving advertisements or optimizing services to You,
Company may allow authorized third parties to place or recognize a unique cookie
on the Your browser. Company does not store personally identifiable information in
the cookies.</p>
<h2 class="terms-title">5. PRICING INFORMATION AND PAYMENT</h2>
<p class="terms-description">Company strives to provide You with the best prices possible on the Products You
require from the Website. The pricing details for purchase of Products from the
Website are detailed under these Terms.
Further:</p>
<ol>
  <li>All commercial terms such as price, delivery, dispatch of Products and/or
services are as per principal-to-principal bipartite contractual obligations
between User and the third parties.</li>
  <li>Your relationship with Company is on a principal-to-principal basis and by
accepting these Terms You agree that Company is an intermediary for all
purposes and does not have control of or liability for the products or services
that are listed/ offered on Company&#39;s Website. Company does not guarantee
the identity of any third parties, nor does it ensure that a User or a third party
will complete a transaction.</li>
  <li>You, as a User, understand that upon initiating a requisition on the Website,
You are entering into a legally binding and enforceable contract with the third
party to purchase the Products and /or Services from the third party on a cash
on delivery basis or such other mode as may be specified by Company.</li>
<li>You, as a User, shall hand over a copy of the prescription, at the time of
delivery, for the delivery of Products which as per law requires a valid
prescription signed by a medical practitioner. You acknowledge that delivery of
such Products shall be made only if the third party or its agent/employee is
satisfied that the prescription is in compliance with applicable laws and norms.</li>
<li>You, as a User, shall electronically notify Company using the appropriate
Company’s Website features immediately upon Delivery or non-Delivery
within the time period as provided in these Terms. Non-notification by You of
delivery or non-delivery within the time period specified in these Terms shall
be deemed as delivery in respect of that particular order.</li>
<li>You, as a User, shall be entitled to claim a refund in accordance with the
Refund and Return Policy of the Company.</li>
<li>Refund shall be made in Indian Rupees only and shall be equivalent wholly or
a part of the Transaction Price received in Indian Rupees.</li>
<li>Refund shall be subject to User complying with these Terms.</li>
<li>Company reserves the right to refuse to process orders/requisitions from
Users with a prior history of questionable charges including without limitation
breach of any agreements by User with Company or breach of any policy.</li>
<li>The User and third-party acknowledge that Company will not be liable for any
damages, interests or claims, etc. resulting from not processing a
transaction/transaction price or any delay in processing a
transaction/transaction price.</li>
<li>You acknowledge that Company is a mere facilitator and does not fall within
the purview of the Food Safety and Standards Act, 2006 and the rules framed
thereunder.</li>
<li>You acknowledge that Company is a mere facilitator and does not fall within
the purview of the Drugs and Cosmetics Act, 1940 and the rules framed
thereunder.</li>
<li>You acknowledge that Company is a mere facilitator/intermediary and does
not fall within the purview of the National Medical Commission Act, 2019, and
the rules and regulations framed thereunder.</li>
<li>The User also agrees to pay a nominal fee as mentioned hereunder.</li>
</ol>  
<p class="terms-description">In order to process the payments for Your orders, the Company might require details
of Your bank account, credit card number, etc. The online fee payments made by
You are processed with the support and services of the banks/payment
gateways/payment aggregators/ third parties and the Company is not responsible for
any loss or damage caused to User/ Retail Pharmacies/ third party service providers
during this process as these banks/payment gateways/payment aggregators/ third
parties are beyond the control of the Company. There are no applicable payment
charges levied on any transactions. Click here to see the list of our available
payment methods and payment partners.<br>Subscription Fee- Any subscription fees for the Services charged by the Company,
could be paid online through the facility made available on the Website. Such online
fee payments are also processed with the support and services of the
banks/payment gateways/payment aggregators/ third parties and the Company is
not responsible for any loss or damage caused to User/ Retail Pharmacies/ third
party service providers during this process as these banks/payment
gateways/payment aggregators/ third parties are beyond the control of the Company.<br>Taxes- Each User / third party service provider is solely responsible for payment of
all taxes, legal compliances, statutory registrations and reporting. The Company
shall in no way be responsible for any of the taxes except for its own taxes. Further
please note that all fees are exclusive of applicable taxes.<br>Security Measures- The payment made for every transaction is done through API
integration. Moreover, You may also check Our Privacy Policy to understand how the
Company uses the confidential information provided by Users.<br>The Company reserves the right to modify the fee structure by providing on the
Website which shall be considered as valid and agreed communication. The
Company shall not be responsible if some purchase is not registered or is lost due to
any network issues/problems such as breakdown of machinery, unclear/ disruption in
the network or non-receipt of payment from banks/payment gateways/payment
aggregators/third parties and/or the cost(s) charged by the network operator(s).
However, the Company shall work towards the best interest of the User.<br>Dispute- Any dispute in connection to the third-parties services shall be settled
between the Users and the respective third parties, including without limitations,
banks/payment gateways/payment aggregators/network operators without involving
the Company.</p>
<h2 class="terms-title">6. USER OBLIGATIONS</h2>
<p class="terms-descripiton">Subject to compliance with these Terms, Company grants You a personal, non-
exclusive, non-transferable, limited privilege to access and use this Website and the
Services provided herein.<br>You agree to use the Services, Website and the materials provided therein only for
purposes that are permitted by: (a) the Terms; and (b) any applicable law, regulation
or generally accepted practices or guidelines in the relevant jurisdictions. You agree
to adhere to all limitations on dissemination, use and reproduction of any materials
(such as the Product catalogues) that You access on the Website in accordance with
Paragraph 7 below. You agree not to access (or attempt to access) the Website and
the materials or services by any means other than through the interface that is
provided by Company. You shall not use any automated means such as data
scraper, deep-link, robot, spider or other automatic device, program, algorithm or
methodology, or any similar or equivalent manual process to access the Website, the
Information, or Services for any purpose. You shall not use any automated device to
access, acquire, copy or monitor any portion of the Website or Content (as defined
below), or in any way reproduce or circumvent the navigational structure or
presentation of the Website, materials or any Content, to obtain or attempt to obtain
any materials, documents or information through any means not specifically made
available through the Website.<br>You acknowledge and agree that by accessing or using the Website or Services, You
may be exposed to content from other Users that You may consider offensive,
indecent or otherwise objectionable. Company disclaims all liabilities arising in
relation to such offensive content on the Website. Further, You may report such
offensive content in the manner prescribed herein. If the Website allows You to post
and upload any material on the Website, You hereby undertake to ensure that such
material is not offensive and in accordance with applicable laws. Further, You
undertake not to:</p>
<ul>
    <li>Host, display, upload, modify, publish, transmit, store, update or share any
    information or user submissions which:</li>
    <ol>
        <li>belongs to another person and to which the user does not have any
        right;</li>
        <li>is pornographic, paedophilic, invasive of another‘s privacy, including
bodily privacy, insulting or harassing on the basis of gender, libellous,
racially or ethnically objectionable, relating or encouraging money
laundering or gambling, or otherwise inconsistent with or contrary to
the laws in force or is objectionable;</li>
        <li>is harmful to child;</li>
        <li>infringes patent, trademark, copyright or other proprietary or intellectual
        property rights;</li>
        <li>violates any law for the time being in force;</li>
        <li>deceives or misleads the addressee about the origin of the message or
knowingly and intentionally communicates any information which is
patently false or misleading in nature but may reasonably be perceived
as a fact;</li>
        <li>threatens the unity, integrity, defence, security or sovereignty of India,
friendly relations with foreign States, or public order, or causes
incitement to the commission of any cognisable offence or prevents
investigation of any offence or is insulting other nation;</li>
        <li>is patently false and untrue, and is written or published in any form,
with the intent to mislead or harass a person, entity or agency for
financial gain or to cause any injury to any person; or threatens public
health or safety;</li>
        <li>Defame, abuse, harass, threaten or otherwise violate the legal rights of
        others; and</li>
        <li>Impersonate any person or entity, or falsely state or otherwise
        misrepresent Your affiliation with a person or entity;</li>
    </ol>
    <li>Publish, post, upload, distribute or disseminate any inappropriate, profane,
defamatory, infringing, obscene, indecent or unlawful topic, name, material or
information through any bookmark, tag or keyword;</li>
    <li>Upload files that contain software or other material protected by applicable
intellectual property laws unless You own or control the rights thereto or have
received all necessary consents;</li>
    <li>Upload or distribute files that contain viruses, corrupted files, or any other
similar software or programs that may damage the operation of the Website or
another&#39;s computer;</li>
    <li>Engage in any activity that interferes with or disrupts access to the Website or
the Services (or the servers and networks which are connected to the
Website);</li>
    <li>Attempt to gain unauthorized access to any portion or feature of the Website,
any other systems or networks connected to the Website, to any Company
server, or to any of the services offered on or through the Website, by
hacking, password mining or any other illegitimate means;</li>
    <li>Probe, scan or test the vulnerability of the Website or any network connected
to the Website, nor breach the security or authentication measures on the
Website or any network connected to the Website. You may not reverse look-
up, trace or seek to trace any information on any other user, of or visitor to,
the Website, or any other customer of Company, including any Company
Account not owned by You, to its source, or exploit the Website or service or
information made available or offered by or through the Website, in any way
whether or not the purpose is to reveal any information, including but not
limited to personal identification information, other than Your own information,
as provided for by the Website;</li>
<li>Disrupt or interfere with the security of, or otherwise cause harm to, the
Website, systems resources, accounts, passwords, servers or networks
connected to or accessible through the Websites or any affiliated or linked
sites;</li>
<li>Collect or store data about other users in connection with the prohibited
conduct and activities set forth in this Paragraph.</li>
<li>Use any device or software to interfere or attempt to interfere with the proper
working of the Website or any transaction being conducted on the Website, or
with any other person&#39;s use of the Website;</li>
<li>Use the Website or any material or Content for any purpose that is unlawful or
prohibited by these Terms, or to solicit the performance of any illegal activity
or other activity which infringes the rights of Company or other third parties;</li>
<li>Conduct or forward surveys, contests, pyramid schemes or chain letters;</li>
<li>Download any file posted by another user of a service that you know, or
reasonably should know, cannot be legally distributed in such manner;</li>
<li>Falsify or delete any author attributions, legal or other proper notices or
proprietary designations or labels of the origin or source of software or other
material contained in a file that is uploaded;</li>
<li>Violate any code of conduct or other guidelines, which may be applicable for
or to any particular Service;</li>
<li>Violate any applicable laws or regulations for the time being in force within or
outside India;</li>
<li>Violate the Terms, including but not limited to any applicable Additional Terms
of the Website contained herein or elsewhere; and</li>
<li>Reverse engineer, modify, copy, distribute, transmit, display, perform,
reproduce, publish, license, create derivative works from, transfer, or sell any
information or software obtained from the Website.</li>
</ul>
<p class="terms-description">Company has no obligation to monitor such communications by You. However,
Company reserves the right to review materials posted by You and to remove any
materials in its sole discretion. Company reserves the right to terminate the User&#39;s
access to any or all of such communication services provided by Company at any
time, without notice for any reason whatsoever. Company reserves the right at all
times to disclose any information as is necessary to satisfy or comply with any
applicable law, regulation, legal process or governmental request, or to edit, refuse
to post or to remove any information or materials, in whole or in part, in Company&#39;s sole discretion. Company does not control or endorse the content, messages or
information found in any communication service and, therefore, Company specifically
disclaims any liability or responsibility whatsoever with regard to the communication
services and any actions resulting from the user&#39;s participation in any communication
service. You agree that You are solely responsible to Company and to any third party
for any breach of Your obligations under the Terms and for the consequences
(including any loss or damage which company or its affiliates or its vendors may
suffer) for any such breach. You agree and acknowledge that Company is not the
owner of the Products and Company shall in no manner be deemed to be the owner
of the Products on this Website. Company is only facilitating purchase of the
Products by You from the third parties by providing the services to You. You agree
that Company may, at any time, modify or discontinue all or part of the Website,
charge, modify or waive fees required to use the Website, or offer opportunities to
some or all Website Users. <br>You agree that the Website shall not be used for illegal purposes. The information
and Services shall not be used for any illegal purpose. You shall not access our
networks, computers, or the information and Services in any manner that could
damage, disable, overburden, or impair them, or interfere with any other person&#39;s
use and enjoyment. You shall not attempt to gain unauthorized access to any
information or Services, other accounts, computer systems, or networks connected
with the Website, the information, or Services. Such unauthorized access includes,
but is not limited to, using another person’s login credentials to access his or her
Company profile/ Account. Any attempt by any individual or entity to solicit login
information of any other user or third party registered medical practitioner or to
access any such account is an express and direct violation of these Terms and of
applicable law(s), including relevant privacy and security laws and laws prohibiting
unfair or unethical business practices.<br>You agree and acknowledge that the exchanges between the third party registered
medical practitioners and You over telephone and the e-prescription would be
accessible to the Company for the purposes of monitoring the quality of the
consultation. The consultation provided by the third-party registered medical
practitioner shall be done vide a secured recorded line.</p>
<h2 class="terms-help-title">Notice and Takedown</h2>
<p class="terms-description">If You believe that any Content on the Website is defamatory, obscene,
pornographic, paedophilic, illegal, offensive, sexually explicit, promotes bigotry,
hatred or physical harm, deceptive, misleading, abusive, indecent, harassing,
blasphemous, defamatory, libellous, invasive of another’s privacy, including bodily
privacy, insulting or harassing on the basis of gender, racially or ethnically
objectionable, relating or encouraging money laundering or gambling; or is otherwise
injurious to third parties; or is harmful to minors in any way; or impersonates another
person; or threatens the unity, integrity, security or sovereignty of any nation or its or
friendly relations with foreign States; or which consists of or contains software
viruses or violates any of the Terms, please notify Us immediately at
support@medizinhub.com. As soon as you inform Us, We will make all reasonable
endeavours to remove such objectionable content complained about within a
reasonable time.</p>
<h2 class="terms-help-title">Risks associated with Company’s Services</h2>
<p class="terms-description">You abide by these Terms, Privacy Policy and any other Company Policy by using
the Company’s Services. The third party registered medical practitioners will not be
examining You physically and may not have access to all or some of Your medical
history that might be critical to consult You. The third party registered medical
practitioners will not have the benefit of information that would be obtained by
examining You in person, observing Your physical condition and by going through
Your medical records. This means that the Services provided is different from the
diagnostic and treatment services typically decided by a physician. Therefore, the
third party registered medical practitioners may not be aware of facts or information
that would affect his or her opinion of Your diagnosis. Therefore, to reduce the risk of
this limitation, the Company strongly encourages You to be in touch with an on-
ground physician and share the third party registered medical practitioners’ opinion
with him/her.
You acknowledge and agree, by requesting a medical opinion through the Website,
that-</p>
<ol>
    <li>the advice/information/opinion on diagnosis You may receive could be limited
    and provisional;</li>
    <li>the medical opinion is not intended to replace a face-to-face visit with a
    physician, and it does not replace an actual doctor-patient relationship;</li>
    <li>in case of a second opinion, where there is a difference of opinion among Our
third party registered medical practitioners and Your physician, You would
bear the responsibility to decide on online or offline consultation, or
procedure, and/or treatment;</li>
    <li>the third party registered medical practitioner is reliant on information provided
by You and hence any information demonstrated to have been falsified,
misleading or incomplete will immediately render the opinion and all details
therein null and void;</li>
    <li>in some events, the third party registered medical practitioners may determine
that the transmitted information is of inadequate quality and may ask for more
information, without which he/she may refuse to answer the query;</li>
    <li>in very rare instances, security protocols could fail, causing a breach of
    privacy of personal medical information; and</li>
    <li>delays in medical evaluation and answers could occur due to deficiencies or
    failures of the service as per those mentioned in these Terms.</li>
    <li>in rare cases, the third party registered medical practitioners may feel that the
query may not be answerable without physically examining the patient/ Users
and the consultation may be refused forthwith;</li>
</ol>
<h2 class="terms-title">7. USE OF MATERIALS</h2>
<p class="terms-description">Except as expressly indicated to the contrary in any applicable Additional Terms,
Company hereby grants You a personal, non-exclusive, freely revocable (upon
notice from Company), non-transferable access to view, download and print product
catalogues or any other materials available on the Website, subject to the following
condition:</p>
<ul>
    <li>You may access and use the materials solely for personal, informational, and
internal purposes, in accordance with the Terms; You may not modify or alter
Product catalogues or any other materials available on the Website;</li>
    <li>You may not distribute or sell, rent, lease, license or otherwise make the
Product catalogues or any other materials available on the Website available
to others; and</li>
    <li>You may not remove any text, copyright or other proprietary notices contained
    in the Product catalogues or any other materials available on the Website.</li>
</ul>
<p class="terms-description">The limited rights granted to You in the Product catalogues, or any other materials as
specified above do not confer upon You any rights to the design, layout or look and
feel of the Website. Such elements of the Website are protected by intellectual
property rights and may not be copied or imitated in whole or in part. The Product
catalogues or any other materials available on the Website shall not be copied or
retransmitted unless expressly permitted by Company. Any software that is available
on the Website is the property of Company or third parties. You may not use,
download or install any software available at the Website, unless otherwise
expressly permitted by these Terms or by the express written permission of
Company.<br>The limited rights granted to You in the Product catalogues, or any other materials as
specified above do not confer upon You any rights to the design, layout or look and
feel of the Website. Such elements of the Website are protected by intellectual
property rights and may not be copied or imitated in whole or in part. The Product
catalogues or any other materials available on the Website shall not be copied or
retransmitted unless expressly permitted by Company. Any software that is available
on the Website is the property of Company or third parties. You may not use,
download or install any software available at the Website, unless otherwise
expressly permitted by these Terms or by the express written permission of
Company.</p>
<h2 class="terms-title">8. USAGE CONDUCT</h2>
<p class="terms-description">You shall solely be responsible for maintaining the necessary computer equipment
and internet connections that may be required to access, use and transact on the
Website.<br>You are also under an obligation to use this Website for reasonable and lawful<br>purposes only, and You shall not indulge in any activity that is not envisaged through
the Website. You shall use this Website, and any voucher/ coupons purchased
through it, for personal, non-commercial use only and You shall not re-sell the same
to any other person. Once you subscribe with the Website, You shall use the
prescription exclusively to purchase medicines via the Website and shall not use the
same prescription to fulfil the medicine requirement from other retailers unless the
medicines are not supplied for any reason via the Website’s partner third parties.</p>
<h2 class="terms-title">9. INTELLECTUAL PROPERTY RIGHTS</h2>
<p class="terms-description">The Website, the processes, and their selection and arrangement, including but not
limited to all text, graphics, user interfaces, visual interfaces, sounds and music (if
any), artwork and computer code (collectively, the &quot;Content&quot;) on the Website is
owned and controlled by Company and the design, structure, selection, coordination,
expression, look and feel and arrangement of such Content is protected by
copyright, patent and trademark laws, and various other intellectual property rights.
The trademarks, logos and service marks displayed on the Website (&quot;Marks&quot;) are the
property of Company or their third party partners or respective third parties. You are
not permitted to use the Marks without the prior consent of Company and/or the
relevant third parties that may own the Marks. Unless otherwise indicated or
anything contained to the contrary or any proprietary material owned by a third party
and so expressly mentioned, Company owns all intellectual property rights in and to
the trademark “medizinhub”, domain name “www.medizinhub.com”, and the Website,
including, without limitation, any and all rights, title and interest in and to copyright,
related rights, patents, utility models, designs, know-how, trade secrets and
inventions (patent pending), goodwill, source code, meta tags, databases, text,
content, graphics, icons, and hyperlinks.<br>Except as expressly provided herein, You acknowledge and agree that You shall not
copy, republish, post, display, translate, transmit, reproduce or distribute any Content
through any medium without obtaining the necessary authorization from Company or
third party owner of such Content.</p>
<h2 class="terms-title">10. RETURN, REFUND, CANCELLATION AND SHIPPING CHARGES:</h2>
<p class="terms-description">We offer return and refund on the products and Services ordered by You on the
Website which are subject to further terms and conditions as detailed in the
cancellation, shipping charges, returns and refund policy (“Return and Refund
Policy”). The <a href="#">Return and Refund Policy</a> forms an integral part of these Terms and the
Users are requested to carefully read the same.</p>
<h2 class="terms-title">11. ADVERTISEMENTS</h2>
<p class="terms-description">As part of the Services provided by Us; We may facilitate and allow third party
advertisers (“Third Party Advertisers”) to place advertisements on the Website.<br><strong>For Users: </strong>The Website clearly distinguishes between the editorial content and
content that is created or provided by one of Our Third Party Advertisers. This
content will not be reviewed by Our in-house editorial staff and shall not be subject to
Our editorial policy (as set out herein below) but shall be subject to applicable laws,
these Terms (except the editorial policy) and the Privacy Policy.<br><strong>For Third Party Advertisers: </strong>The Third Party Advertisers must be honest about the
products or services their advertisements promote; the advertisement shall not
create unrealistic expectation and must not be misleading or offending; must be
responsible and of the highest standards and without compromising consumer
protection.<br><strong>General Rules: </strong>The Company may, at any time and without having to serve any
prior notice to the Third Party Advertisers, (i) upgrade, update, change, modify, or
improve the Website or a part thereof in a manner it may deem fit, and (ii) change
the content of the Advertising Policy and/ or these Terms and/ or the Privacy Policy.
It is the responsibility of the Third Party Advertisers, in such cases, to review the
terms of the Advertising Policy and/ or these Terms and/ or the Privacy Policy, from
time to time. Such change shall be made applicable when they are posted. We may
also alter or remove any content from the Website without notice and without liability.
The Third Party Advertisers are also responsible for ensuring that their
advertisements comply with all applicable law(s) in India and any other jurisdiction
that such Third Party Advertiser(s) are based out of, industry codes, rules and
regulations in each geographic area where the advertisements will run. All
disclosures in the advertisements must be clear and conspicuous. We are not
responsible for any liability arising from an advertisement by a Third Party Advertiser.
The Company reserves the right to reject or remove any advertisement in its sole
discretion for any reason. Further, the Company also reserves the right to request
modifications to any advertisement, and to require factual substantiation for any
claim made in an advertisement.</p>
<h2 class="terms-title">12. EDITORIAL POLICY</h2>
<p class="terms-description">As part of the Services provided by Us, the Website provides editorial content
targeted at the public for informational purposes only and such editorial content does
not constitute professional medical advice, diagnosis, treatment or recommendations
of any kind. Users are requested to carefully read the <a href="">Editorial Policy</a>.</p>
<h2 class="terms-title">13. DISCLAIMER OF WARRANTIES AND LIABILITIES</h2>
<p class="terms-description">You expressly understand and agree that, to the maximum extent permitted by
applicable law the Website, services and other materials are provided by Company
on an &quot;as is&quot; basis without warranty of any kind, express, implied, statutory or
otherwise, including the implied warranties of title, non-infringement, merchantability
or fitness for a particular purpose. Without limiting the foregoing, Company makes no
warranty that (i) the Website or the services will meet your requirements or your use
of the Website or the services will be uninterrupted, timely, secure or error-free; (ii)
the results that may be obtained from the use of the Website, services or materials will be effective, accurate or reliable; (iii) the quality of the Website, services or other
materials will meet your expectations; or that (iv) any errors or defects in the
Website, services or other materials will be corrected. No advice or information,
whether oral or written, obtained by you from Company or through or from use of the
services shall create any warranty not expressly stated in the Terms.
To the maximum extent permitted by applicable law, Company will have no liability
related to user content arising under intellectual property rights, libel, privacy,
publicity, obscenity or other laws. Company also disclaims all liability with respect to
the misuse, loss, modification or unavailability of any user content.
Company will not be liable for any loss that You may incur as a consequence of
unauthorized use of Your Account or Account Information in connection with the
Website or any services or materials, either with or without your knowledge.
Company has endeavoured to ensure that all the information on the Website is
correct, but Company neither warrants nor makes any representations regarding the
quality, accuracy or completeness of any data, information, product or service.
Company shall not be responsible for the delay or inability to use the Website or
related functionalities, the provision of or failure to provide functionalities, or for any
information, software, products, functionalities and related graphics obtained through
the Website, or otherwise arising out of the use of the Website, whether based on
contract, tort, negligence, strict liability or otherwise. Further, Company shall not be
held responsible for non-availability of the Website during periodic maintenance
operations or any unplanned suspension of access to the Website that may occur
due to technical reasons or for any reason beyond Company&#39;s control. The User
understands and agrees that any material or data downloaded or otherwise obtained
through the Website, is done entirely at their own discretion and risk and they will be
solely responsible for any damage to their computer systems or loss of data that
results from the download of such material or data. Company is not responsible for
any typographical error leading to an invalid coupon. Company accepts no liability for
any errors or omissions, with respect to any information provided to you whether on
behalf of itself or third parties.<br>Company shall not be liable for any third-party product or services. The
advertisement available on e-mail or Website with respect to the third-party website
or the Products are for information purpose only. You expressly agree that Your use
of the Website is at Your risk.</p>
<h2 class="terms-title">14. INDEMNIFICATION AND LIMITATION OF LIABILITY</h2>
<p class="terms-description">You agree to indemnify, defend and hold harmless Company including but not limited
to its affiliates, vendors, representatives, directors, agents and employees from and
against any and all losses, liabilities, claims, damages, demands, costs and
expenses (including legal fees and disbursements in connection therewith and
interest chargeable thereon) asserted against or incurred by Company that arise out
of, result from, or may be payable by virtue of, any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be
performed by You pursuant to these Terms. Further, You agree to hold Company
harmless against any claims made by any third party due to, or arising out of, or in
connection with, Your use of the Website, any claim that Your material caused
damage to a third party, Your violation of the Terms, or Your violation of any rights of
another, including any intellectual property rights. Notwithstanding anything to
contrary, Company&#39;s entire liability to You under this Terms or otherwise shall be to
the extent of refund of the money charged from You for any specific voucher or
Product or service, under which the unlikely liability arises. In no event shall
Company, its officers, directors, employees, partners or suppliers be liable to You,
the vendor or any third party for any special, incidental, indirect, consequential or
punitive damages whatsoever, including those resulting from loss of use, data or
profits, whether or not foreseeable or whether or not Company has been advised of
the possibility of such damages, or based on any theory of liability, including breach
of contract or warranty, negligence or other tortious action, or any other claim arising
out of or in connection with Your use of or access to the Website, services or
materials. Company is not responsible for any non-performance or breach of any
contract entered into between Users and third party service providers. Company
cannot and does not guarantee that the concerned Users and/or third party service
providers will perform any transactions that are entered into on the Website.
Company shall not and is not required to mediate or resolve any dispute or
disagreement between Users and third party service providers. Company does not,
at any point of time during any transaction between Users and third party service
providers on the Website come into or take possession of any of the Products or
Services offered by third party service providers nor does it at any point gain title to
or have any rights or claims over the Products or Services offered by third party
service providers to Users.<br>At no time shall Company hold any right, title or interest over the products, nor shall
Company have any obligations or liabilities in respect of such contract entered into
between Users and third party service providers. Company is not responsible for any
unsatisfactory or delayed performance of services or damages or delays as a result
of products which are out of stock, unavailable or back ordered. The limitations and
exclusions in this section apply to the maximum extent permitted by applicable law.</p>
<h2 class="terms-title">15. VIOLATION OF TERMS</h2>
<p class="terms-description">You agree that Company may, in its sole discretion and without prior notice,
terminate Your access to the Website and block Your future access to the Website, if
Company determines that You have violated these Terms or Additional Terms. You
also agree that any violation by You of these Terms will constitute an unlawful and
unfair business practice, and will cause irreparable harm to Company, for which
monetary damages would be inadequate, and You consent to Company obtaining
any injunctive or equitable relief that Company deems necessary or appropriate in
such circumstances. These remedies are in addition to any other remedies Company
may have at law or in equity. You agree that Company may, in its sole discretion, and
without prior notice, terminate Your access to the Website, for cause, which includes
(but is not limited to): (1) requests by law enforcement or other government
agencies; (2) a request by You (self-initiated account deletions); (3) discontinuance
or material modification of the Website or any service offered on or through the
Website; or unexpected technical issues or problems. If Company does take any
legal action against You as a result of Your violation of these Terms, Company will be
entitled to recover from You, and You agree to pay, all reasonable attorneys&#39; fees
and costs of such action, in addition to any other relief granted to Company.</p>
<h2 class="terms-title">16. TERMINATION</h2>
<p class="terms-description">The Terms will continue to apply until terminated by either You or Company as set
forth below. If You want to terminate Your agreement with Company, You may do so
by (i) not accessing the Website; or (ii) closing Your accounts for all of the services
that You use, where Company has made this option available to You.
Company may, at any time, with or without notice, terminate the Terms (or portion
thereof, such as any individual Additional Terms) with You if:</p>
<ul>
    <li>You breach any of the provisions of the Terms, the Privacy Policy or any other
terms, conditions, or policies that may be applicable to You from time to time
(or have acted in a manner that clearly shows that You do not intend to, or are
unable to, comply with the same);</li>
    <li>Company is required to do so by law (for example, where the provision of the
    services hereunder, to You is, or becomes, unlawful);</li>
    <li>The provision of the services to You, by Company is, in Company&#39;s opinion,
    no longer commercially viable;</li>
    <li>Company has elected to discontinue, with or without reason, access to the
    Website, the services (or any part thereof); or</li>
    <li>Company may also terminate or suspend all or a portion of Your account or
    access to the services with or without reason.</li>
</ul>
<p class="terms-description">Except as may be set forth in any Additional Terms applicable to a particular service,
termination of Your Account may include: (i) removal of access to all offerings within
the Website or with respect to the services; (ii) deletion of Your materials and
Account Information, including Your personal information, log-in ID and password,
and all related information, files and materials associated with or inside Your Account
(or any part thereof); and (iii) barring of further use of the Services.
You agree that all terminations shall be made in Company&#39;s sole discretion and that
Company shall not be liable to You or any third party for any termination of Your
Account (and accompanying deletion of Your Account Information), or Your access to
the Website and the services offered thereunder.<br>Notwithstanding the foregoing, these Terms will survive indefinitely unless and until
Company chooses to terminate them. If You or Company terminates Your use of the
Website, Company may delete any content or any other materials relating to Your
use of the Website and Company will have no liability to You or any third party for
doing so.</p>
<h2 class="terms-title">17. GOVERNING LAW</h2>
<p class="terms-description">These Terms and all transactions entered into on or through the Website and the
relationship between You and Company shall be governed in accordance with the
laws of India without reference to conflict of laws principles.
You agree that all claims, differences and disputes arising under or in connection
with or in relation hereto the Website, the Terms or any transactions entered into on
or through the Website or the relationship between You and Company shall be
subject to the exclusive jurisdiction of the courts at Mumbai, India and You hereby
accede to and accept the jurisdiction of such courts.</p>
<h2 class="terms-title">18. GOVERNING LAW</h2>
<p class="terms-description">These Terms and all transactions entered into on or through the Website and the
relationship between You and Company shall be governed in accordance with the
laws of India without reference to conflict of laws principles.
You agree that all claims, differences and disputes arising under or in connection
with or in relation hereto the Website, the Terms or any transactions entered into on
or through the Website or the relationship between You and Company shall be
subject to the exclusive jurisdiction of the courts at Mumbai, India and You hereby
accede to and accept the jurisdiction of such courts.</p>
<h2 class="terms-title">19. REPORT ABUSE / GRIEVANCE REDRESSAL</h2>
<p class="terms-description">In the event You come across any abuse or violation of these Terms or if You
become aware of any objectionable content on the Website, please report to
Company’s customer support team.<br>If You have any concern about the Terms or grievances about the Website or our
services, please contact us with a thorough description and We will try to resolve the
issue for You. Please address them to Our grievance redressal officer at:
Please see below the details of our grievance officer:</p>
<h2 class="terms-help-title">Name: Mr. N. Balaji</h2>
<h2 class="terms-help-title">Email:  support@medizinhub.com</h2>
<p class="terms-description"><strong>Address: </strong>112, Bharath Flats, RadhaNagar Main Road, Chromepet, Chennai-600
044, Tamil Nadu, India</p>
<h2 class="terms-help-title">Mobile Number: 9047660909</h2>
<p class="terms-description">While we strive to address all grievances internally, we acknowledge that certain
issues may be best resolved directly between you and the Retail Pharmacies/Labs.
In such cases, We will facilitate this process by forwarding your grievance to the
relevant Retail Pharmacies/Labs to ensure a prompt and effective resolution.
However, our Grievance Officer shall continue to serve as the primary point of
contact for any concerns related to the services provided on our platform.</p>
<h2 class="terms-title">20. PRIVACY POLICY</h2>
<p class="terms-description">Company collects, processes and shares data with third parties, in accordance with
its Privacy Policy, in order to provide, manage and complete delivery of products and services requested by You . Company views the protection of Your privacy and
information as a very important principle. Please view Our Privacy Policy, available
at <a href="">www.medizinhub.com./legal/privacy-policy</a>, to understand how the Company
collects, processes, shares Your information and maintains data security practices in
relation to Your information.</p>
<h2 class="terms-title">21. COMMUNICATIONS</h2>
<p class="terms-description">You hereby expressly agree to receive communications by way of SMS, e-mails or
any other mode from Company, phone calls relating to the Products offered through
the Website and this supersedes any opt-out preferences you may have set in
relation to the Telecom Regulatory Authority of India’s National Do Not Call (and Do
Not Disturb) registry as per the Telecom Commercial Communications Customer
Preference Regulations, 2018.<br>A User can unsubscribe / opt-out from receiving communications from Company
through SMS and e-mail anytime by:</p>
<ul>
    <li>Visiting <a href="">www.medizinhub.com</a> to unsubscribe from messages/ SMS; and</li>
    <li>Newsletters sent daily at the registered email address and by clicking on the
unsubscribe option attached at the bottom of newsletter received through e-
mail.</li>
</ul>
<h2 class="terms-title">22. GENERAL PROVISIONS</h2>
<p class="terms-description"><strong>Notice: </strong>All notices of Company will be served by email or by general notification on
the Website. Any notice provided to Company pursuant to the Terms should be sent
to support@medizinhub.com <br>
<strong>Assignment: </strong>You cannot assign or otherwise transfer the Terms, or any rights
granted hereunder to any third party. Company&#39;s rights under the Terms are freely
transferable by Company to any third parties without the requirement of seeking Your
consent. <br>
<strong>Severability: </strong>If, for any reason, a court of competent jurisdiction finds any provision
of these Terms, or portion thereof, to be unenforceable, that provision shall be
enforced to the maximum extent permissible so as to give effect to the intent of the
parties as reflected by that provision, and the remainder of the Terms shall continue
in full force and effect. <br>
<strong>Waiver: </strong>Any failure by Company to enforce or exercise any provision of the Terms,
or any related right, shall not constitute a waiver by Company of that provision or
right <br></p>