<style>
    main{
        display: none !important;
    }
    .confirm-img p{
        color: var(--Black-font, #313739);
        font-family: "Source Sans Pro";
        font-size: 28px;
        font-style: normal;
        font-weight: 600;
        line-height: normal;
    }
    .page-title-wrapper{
        display: none;
    }

    .confirm-img span{
        color: #03B26B;
        font-family: "Source Sans Pro";
        font-size: 28px;
        font-style: normal;
        font-weight: 700;
        line-height: normal;
    }
    .confirm-order{
        padding: 0 172px;
    }
</style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<div class="confirm-order">
    <div class="container">
        <div class="row">
        <p style="color: #063851;font-family: Source Sans Pro,Sans-serif;font-size: 24px;font-weight: 600;">Final Step to Confirm your order</p>
<div class="col-md-12">
    <div class="confirm-img">
<img width="436px" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/orderconfirm.png'); ?>" alt="">
<p>Give a missed call to <span>90476 60909</span>, and confirm you slot now. </p>
</div>
</div>
        </div>
    </div>
</div>

<div class="mobile_qr">
    <a href="https://play.google.com/store/apps/details?id=com.mhb.medizin_hub" target="_blank">
        <img src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/mobile_qr.png'); ?>" alt="MedizinHub Mobile App"  title="MedizinHub Mobile App" class="mobile_qr_img">
    </a>
</div>
