<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Catalog\Block\Product\View\Details $block */
$baseUrl = $this->getBaseUrl();
$safetyImage = $baseUrl .'/static/frontend/ET/base_lite/en_US/MedizinhubCore_Home/images/safety.png';
?>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) : ?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <div class="data item content-description">
                <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $registry = $objectManager->get('\Magento\Framework\Registry');
                $currentProduct = $registry->registry('current_product');

                if ($currentProduct) {
                    $description = $currentProduct->getData('description');
                    $product_details = $currentProduct->getData('product_details');
                    $usesofproduct = $currentProduct->getData('uses_of_product');
                    $direction = $currentProduct->getData('direction_for_use');
                    $sideAffectsValue = $currentProduct->getData('side_affects');
                    $safety = $currentProduct->getData('safety_advices');
                    $additional = $currentProduct->getData('additional_details');

                    if ($description !== null && $description !== '') {
                        $description_length = str_word_count($description);
                        if ($description_length > 150) {
                            $short_description = implode(' ', array_slice(str_word_count($description, 1), 0, 50));
                            echo "<p class='product-description'>Description</p>";
                            echo "<p class='product-description-content'>" . $short_description . "<span id='dots'>...</span><span id='more' style='display: none;'>" . substr($description, strlen($short_description)) . "</span><span style='font-size:16px;padding: 0 4px;font-weight:600; cursor: pointer;' onclick='readMore()' id='read-more-btn'>Read more</span></p>";
                            echo "<script>
                                    function readMore() {
                                        var dots = document.getElementById('dots');
                                        var moreText = document.getElementById('more');
                                        var btnText = document.getElementById('read-more-btn');

                                        if (dots.style.display === 'none') {
                                            dots.style.display = 'inline';
                                            btnText.innerHTML = 'Read more';
                                            moreText.style.display = 'none';
                                        } else {
                                            dots.style.display = 'none';
                                            btnText.innerHTML = 'Read less';
                                            moreText.style.display = 'inline';
                                        }
                                    }
                                    </script>";
                        } else {
                            echo "<p class='product-description'>Description</p>";
                            echo "<p class='product-description-content'>" . htmlspecialchars($description, ENT_QUOTES, 'UTF-8') . "</p>";
                        }
                    }
                    echo "<p style='
                            background: #E7F5FD;
                            border-radius: 8px;
                            font-size: 18px;
                            padding: 10px 20px;
                            display: inline-block;
                            margin-right: 50px;
                            margin-top:10px;
                            font-family: Source Sans Pro;' class='securely-description'>
                             <img class='safety-secure' src='" . $safetyImage . "' style='vertical-align: middle; margin-right: 10px; margin-top: -6px;'>
                            All the items have been securely packed and stored
                        </p>";

                    if ($product_details !== null && $product_details !== '') {
                        echo "<p class='product-description'>Product Details</p>";
                        echo "<p class='product-description-content'>" . $product_details . "</p>";
                    }
                    if ($usesofproduct !== null && $usesofproduct !== '') {
                        echo "<p class='product-description'>Uses of Product</p>";
                        echo "<p class='product-description-content'>" . $usesofproduct . "</p>";
                    }
                    if ($direction !== null && $direction !== '') {
                        echo "<p class='product-description'>Direction For Use</p>";
                        echo "<p class='product-description-content'>" . $direction . "</p>";
                    }
                    if ($sideAffectsValue !== null && $sideAffectsValue !== '') {
                        echo "<p class='product-description'>Side Affects</p>";
                        echo "<p class='product-description-content'>" . $sideAffectsValue . "</p>";
                    }
                    if ($safety !== null && $safety !== '') {
                        echo "<p class='product-description'>Safety Advices</p>";
                        echo "<p class='product-description-content'>" . $safety . "</p>";
                    }
                    if ($additional !== null && $additional !== '') {
                        echo "<p class='product-description'>Additional Details</p>";
                        echo "<p class='product-description-content'>" . $additional . "</p>";
                    }
                }
                ?>
                <p class='product-description disclaimer lato-regular addition-description'>Disclaimer</p>
                <p class='product-description-content lato-regular addition-description'>The contents of this website are for informational purposes only and not intended to be a substitute for professional medical advice, diagnosis, or treatment. Please seek the advice of a physician or other qualified health provider with any questions you may have regarding a medical condition. Do not disregard professional medical advice or delay in seeking it because of something you have read on this website.
                </p>
            </div>
        </div>
    </div>
    <style>
 .addition-description{color: #868686;text-align: justify;font-size: 14px; }.disclaimer{font-size:16px !important}.lato-regular { font-family: "Lato", sans-serif !important; font-weight: 400 !important;font-style: normal !important;}
    </style>
<?php endif; ?>
