<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<?php
/** @var \Magento\Framework\App\ObjectManager $objectManager */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$practitionersQuery = "SELECT id, name , mrp ,special_price FROM practitioners WHERE status = 1";
$practitioners = $connection->fetchAll($practitionersQuery);
$hospitalsQuery = "SELECT id, name FROM hospitals WHERE status = 1";
$hospitals = $connection->fetchAll($hospitalsQuery);
$timeSlotsQuery = "SELECT id, slot_time FROM time_slots WHERE status = 1";
$timeSlots = $connection->fetchAll($timeSlotsQuery);
/** @var \MedizinhubCore\Patient\Block\Patient $block */
$patientCollection = $block->getPatientData();

function formatDateToDDMMYYYY($date)
{
    if (!empty($date)) {
        $dateObj = new DateTime($date);
        return $dateObj->format('d/m/Y');
    }
    return '';
}

$formattedPatients = '';
$firstPatient = true;
$firstPatientId = '';

foreach ($patientCollection as $patient) {
    $checked = $firstPatient ? 'checked' : '';

    $nameParts = explode(' ', $patient['name']);
    $firstName = isset($nameParts[0]) ? $nameParts[0] : '';
    $lastName = isset($nameParts[1]) ? $nameParts[1] : '';

    $formattedDob = '';
    if (!empty($patient['date_of_birth'])) {
        $date = new \DateTime($patient['date_of_birth']);
        $formattedDob = $date->format('d/m/Y');
    }

    $lastTwoDigitsOfPincode = isset($patient['postcode']) ? substr($patient['postcode'], -2) : '00';
    $formattedPatients .= '<div class="patient-preview" data-patient-id="' . $patient['id'] . '">';
    $formattedPatients .= '<hr class="patient-break-line">';
    $formattedPatients .= '<input type="radio" name="patient_entity" value="' . $patient['id'] . '" data-patient-id="' . $patient['id'] . '" ' . $checked . '>';
    $formattedPatients .= '<br><strong>' . ucfirst($firstName) . ' ' . ucfirst($lastName) . ' ( Age : ' . $patient['age'] . ') (' . ucfirst($patient['gender']) . ')</strong> ';
    $formattedPatients .= $patient['house_no'] . ', ' . $patient['street'] . ', ' . $patient['area'] . ', Chennai-[Ch-' . $lastTwoDigitsOfPincode . ']<br>';
    $formattedPatients .= 'Blood Group: ' . $patient['blood_group'] . ', Ph.No: ' . $patient['phone'] . ', WhatsApp.No: ' . $patient['whatsapp'] . ', Email.Id: ' . $patient['email'] . '<br>';
    $formattedPatients .= '<a href="#" class="edit-patient"
        data-patient-id="' . $patient['id'] . '"
        data-firstname="' . $firstName . '"
        data-lastname="' . $lastName . '"
        data-age="' . $patient['age'] . '"
        data-gender="' . $patient['gender'] . '"
        data-house-no="' . $patient['house_no'] . '"
        data-area="' . $patient['area'] . '"
        data-street="' . $patient['street'] . '"
        data-city="' . $patient['city'] . '"
        data-pincode="' . $patient['postcode'] . '"
        data-telephone="' . $patient['phone'] . '"
        data-whatsapp="' . $patient['whatsapp'] . '"
        data-region-id="' . $patient['region_id'] . '"
        data-email="' . $patient['email'] . '"
        data-dob="' . $patient['date_of_birth'] . '"
        data-blood-group="' . $patient['blood_group'] . '">Edit</a> | ';
    $formattedPatients .= '<a href="#" class="delete-patient" data-patient-id="' . $patient['id'] . '" onclick="patientChecker()">Delete</a><br><br>';
    $formattedPatients .= '</div>';

    $firstPatient = false;
}

$hasPatients = !empty($formattedPatients);
$addNewPatient = '<a href="#" class="action submit primary" id="modal-btn" style="margin: 0 137px"><span>+ Add Patient</span></a>';
?>

<div class="container patient">
    <form class="form patientform" id="patient-form" method="post" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" enctype="multipart/form-data" data-mage-init='{"validation":{}}' onsubmit="return submitForm()">
        <div class="step-titles">
            <div class="step-title active" data-step="1">Select Patient</div>
            <div class="step-line"></div>
            <div class="step-title" data-step="2">Doctor Consultation Details</div>
            <div class="step-line"></div>
            <div class="step-title" data-step="3">Payment</div>
        </div>
        <div class="display_patient">
            <fieldset class="fieldset step" data-step="1">
                <div class="upload-now-addr" id="patient-page">
                    <?php if (!empty($formattedPatients)) { ?>
                        <div id="existing-patient-container">
                            <div id="edit-patient-form">
                                <div class="patient-container" id="update-patient-list">
                                    <?php echo $formattedPatients; ?>
                                </div>
                                <?php echo $addNewPatient; ?>
                            </div>
                        </div>
                    <?php } else { ?>
                        <div id="existing-patient-container">
                            <div id="edit-patient-form">
                                <div class="patient-label-page">
                                    <label class="patient-label"><?= $block->escapeHtml(__('Select Patient')) ?></label>
                                </div>
                                <div class="patient-container" id="update-patient-list">
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </fieldset>
            <fieldset class="fieldset step" data-step="2" style="display: none;">
                <div class="container patient-addr" id="patient-add-new-details">
                    <div class="add-patient-label-page">
                        <label class="patient-label"><?= $block->escapeHtml(__('Doctor Consultation Details')) ?></label>
                    </div>
                    <div class="row">
                        <div class="col-md-8 col-xs-8 col-sm-8 col-lg-8">
                            <div>
                                <input type="hidden" id="selected-patient-id" name="patient_id" value="<?= $firstPatientId ?>">
                            </div>
                            <div class="field practitioners required">
                                <label for="practitioners" class="label practitioners patient-form-label">
                                    <span><?= $block->escapeHtml(__('Select Doctor/Practitioners')) ?></span>
                                    <span class="required-asterisk">*</span>
                                </label>
                                <div class="control patient-input">
                                <select name="practitioner_id" id="practitionersDropdown" title="<?= $block->escapeHtmlAttr(__('Practitioners')) ?>" class="practitioner-input-dropdown patient-input-text" required>
                                   <option value="">Select Practitioner</option>
                                     <?php foreach ($practitioners as $practitioner) : ?>
                                   <option value="<?= $practitioner['id']; ?>" data-mrp="<?= $practitioner['mrp']; ?>"
                                   data-special-price="<?= $practitioner['special_price']; ?>"><?= $block->escapeHtml($practitioner['name']); ?></option>
                                     <?php endforeach; ?>
                                </select>
                                    <div class="practitioner-form-error-message" id="practitioner-error-message"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8 col-xs-8 col-sm-8 col-lg-8">
                            <div class="field hospitals required">
                                <label for="hospital_id" class="label hospitals patient-form-label">
                                    <span><?= $block->escapeHtml(__('Select Hospital')) ?></span>
                                    <span class="required-asterisk">*</span>
                                </label>
                                <div class="control patient-input">
                                <select name="hospitals" id="hospitalDropdown" title="<?= $block->escapeHtmlAttr(__('Hospitals')) ?>" class="hospital-input-dropdown patient-input-text" required>
    <option value="">Select Hospital</option>
    <?php foreach ($hospitals as $hospital) : ?>
        <option value="<?= $hospital['id']; ?>" <?= $hospital['id'] == 1 ? 'selected' : ''; ?>>
            <?= $block->escapeHtml($hospital['name']); ?>
        </option>
    <?php endforeach; ?>
</select>
                                    <div class="hospital-form-error-message" id="hospital-error-message"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8 col-xs-8 col-sm-8 col-lg-8">
                            <div class="field date required">
                                <label for="date" class="label date patient-form-label">
                                    <span><?= $block->escapeHtml(__('Select Date')) ?></span>
                                    <span class="required-asterisk">*</span>
                                </label>
                                <div class="control patient-input" style="position: relative;">
                                    <input type="text" name="appointment_date" id="appointment_date" class="required-entry patient-input-text" data-validate="{required: true}" style="padding-right: 40px;" />
                                    <div class="date-error-message" id="date-error-message" style="color: red; display: none;"></div>
                                    <span class="calendar-icon" style="position: absolute; right: 10px; top: 45%; transform: translateY(-50%); cursor: pointer;">
                                        <img src="<?= $block->getViewFileUrl('MedizinhubCore_Patient::images/calendar-date.svg') ?>" alt="Calendar Icon" style="width: 20px; height: 20px;">
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8 col-xs-8 col-sm-8 col-lg-8">
                            <div class="field time required">
                                <label for="time_slot" class="label time patient-form-label">
                                    <span><?= $block->escapeHtml(__('Select Time Slot')) ?></span>
                                    <span class="required-asterisk">*</span>
                                </label>
                                <div class="control patient-input">
                                <select name="time_slot" id="time_slot" class="select required-entry patient-input-text" data-validate="{required:true}">
                             <option value="0"><?= $block->escapeHtml(__('Please select a time slot')) ?></option>
                                <?php foreach ($timeSlots as $timeSlot) : ?>
                           <option value="<?= $timeSlot['id']; ?>"><?= $block->escapeHtml($timeSlot['slot_time']); ?></option>
                                <?php endforeach; ?>
                                  </select>
                                    <div class="time-slot-error-message" id="time-slot-error-message" style="color: red; display: none;"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                            <div class="field description required">
                                <label for="description" class="label description patient-form-label">
                                    <span><?= $block->escapeHtml(__('Describe the patient issue')) ?></span>
                                    <span class="required-asterisk">*</span>
                                </label>
                                <div class="control patient-input">
                                    <textarea name="patient_issue" id="description" title="<?= $block->escapeHtmlAttr(__('Description')) ?>" class="patient-input-text required-entry" cols="5" rows="3" data-validate="{required:true}" maxlength="500" placeholder="<?= $block->escapeHtmlAttr(__('Please describe the patient\'s issue here...')) ?>"></textarea>
                                    <div id="char-count">500 characters remaining</div>
                                    <div class="description-error-message" id="description-error-message" style="color: red; display: none;"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-10 col-xs-10 col-sm-10 col-lg-10">
                            <div class="upload-img-btn">
                                <div class="field upload-report required">
                                    <label for="upload-report" class="label upload-report patient-form-label">
                                        <span><?= $block->escapeHtml(__('Upload report')) ?></span>
                                        <span style="font-weight: lighter;">(Optional)</span>
                                    </label>
                                    <div class="field image-upload">
                                        <div id="image-preview-container"></div>
                                        <div id="file-input-container" style="display: none;"></div>
                                        <label class="label" id="prescription-label" onclick="checkAndAddFileInput()">
                                            <img src="<?= $block->getViewFileUrl('MedizinhubCore_Patient::images/Prescription-Img.svg') ?>" alt="Prescription-Img">
                                        </label>
                                        <div id="error-message" style="color: red;"></div>
                                    </div>
                                    <p class="note" id="prescription-refe">
                                        <span class="note-text">Note: </span>It's better to discuss the issue during consulting.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
            <fieldset class="fieldset step" data-step="3" style="display: none;">
                <div class="container">
                    <div class="add-patient-label-page">
                        <label class="patient-label"><?= $block->escapeHtml(__('Select Your Payment Method')) ?></label>
                    </div>
                    <div class="row patient-3-cont">
                        <div class="col-md-8 col-12">
                            <div class="payment-method">
                                <ul>
                                    <li>
                                        <input type="radio" id="razorpay" name="payment_method" value="razorpay" checked>
                                        <label for="razorpay">Pay Online<span class="razorpay-helper-text">(Card, Online Transactions)</span></label>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-4 col-12">
                            <div class="pricing-details">
                                <p class="price-header">Pricing Details</p>
                                <h4 class="fee-text">Doctor Fee (Include Tax) <span class="home-visit-fee" id="doctor-fee">₹450</span></h4>
                                <h4 class="fee-text">Discount <span class="discount-offer">50% OFF</span><span class="home-visit-fee" id="discount">- ₹150</span></h4>
                                <hr class="pricing-line">
                                <h4 class="total-fee">Total Amount to Pay <span class="home-visit-fee" id="total-amount">₹300</span></h4>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
            <div class="actions-toolbars upload-button" style="width:100%; text-align:center;">
                <div class="primary" id="button-container">
                    <button type="button" class="action submit primary btn-navigate-form-step" id="next-step-btn" <?php if (empty($formattedPatients)) echo 'style="display:none;"'; ?>>
                        <span>Book Doctor</span>
                    </button>
                    <button id="book-appointment-btn" type="button" class="action submit primary btn-navigate-form-step" style="display: none;" disabled>
                        <span>Book Appointment</span>
                    </button>
                    <button id="cod-btn" type="button" class="action submit primary btn-navigate-form-step" style="display: none;">
                        <span>Book Now</span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
<div id="modal-content" style="display: none;">
    <div class="container patient-addr" id="patient-add-new-addr">
        <div class="add-patient-label-page">
            <label class="patient-label"><?= $block->escapeHtml(__('Add New Patient')) ?></label>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field firstname required">
                    <label class="label firstname patient-form-label" for="firstname"><span><?= $block->escapeHtml(__('First Name')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="firstname" id="addfirstname" placeholder="Enter your first name" title="<?= $block->escapeHtmlAttr(__('First Name')) ?>" class="patient-input-text" type="text" pattern="^[a-zA-Z]{2,}$" required />
                        <div class="patient-form-error-message" id="firstname-patient-error-message"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field lastname required">
                    <label class="label lastname patient-form-label" for="lastname"><span><?= $block->escapeHtml(__('Last Name')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="lastname" id="addlastname" placeholder="Enter your last name" title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>" class="patient-input-text" type="text" pattern="^[a-zA-Z]{2,}$" required />
                        <div class="patient-form-error-message" id="lastname-patient-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field customer_email required">
                    <label class="label customer_email patient-form-label" for="customer_email"><span><?= $block->escapeHtml(__('Email ID')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="customer_email" id="addcustomer_email" placeholder="Enter valid Email Address" title="<?= $block->escapeHtmlAttr(__('Email ID')) ?>" class="patient-input-text" type="email" pattern="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}" required />
                        <div class="patient-form-error-message" id="email-patient-error-message"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field customer_gender required">
                    <label class="label customer_gender patient-form-label" for="customer_gender"><span><?= $block->escapeHtml(__('Gender')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <select name="customer_gender" id="addcustomer_gender" title="<?= $block->escapeHtmlAttr(__('Gender')) ?>" class="patient-input-text" required>
                            <option value="" selected disabled><?= $block->escapeHtml(__('Select Gender')) ?></option>
                            <option value="male"><?= $block->escapeHtml(__('Male')) ?></option>
                            <option value="female"><?= $block->escapeHtml(__('Female')) ?></option>
                            <option value="transgender"><?= $block->escapeHtml(__('Transgender')) ?></option>
                        </select>
                        <div class="patient-form-error-message" id="gender-patient-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field dob required">
                    <label class="label dob patient-form-label" for="dob"><span><?= $block->escapeHtml(__('Date of Birth')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input" style="position: relative;">
                        <input name="dob" id="adddob" title="<?= $block->escapeHtmlAttr(__('Date of Birth')) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Select Date of Birth')) ?>" class="patient-input-text" type="text" required style="padding-right: 40px;" />
                        <div class="patient-form-error-message" id="dob-patient-error-message"></div>
                        <span class="calendar-icon" style="position: absolute; right: 10px; top: 45%; transform: translateY(-50%); cursor: pointer;">
                            <img src="<?= $block->getViewFileUrl('MedizinhubCore_Patient::images/calendar-date.svg') ?>" alt="Calendar Icon" style="width: 20px; height: 20px;">
                        </span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field blood_group required">
                    <label class="label blood_group patient-form-label" for="blood_group"><span><?= $block->escapeHtml(__('Blood Group')) ?></span></label>
                    <div class="control patient-input">
                        <select name="blood_group" id="addblood_group" title="<?= $block->escapeHtmlAttr(__('Blood Group')) ?>" class="patient-input-text" required>
                            <option value="" selected disabled><?= $block->escapeHtml(__('Select Blood Group')) ?></option>
                            <option value="A+"><?= $block->escapeHtml(__('A Positive')) ?></option>
                            <option value="A-"><?= $block->escapeHtml(__('A Negative')) ?></option>
                            <option value="B+"><?= $block->escapeHtml(__('B Positive')) ?></option>
                            <option value="B-"><?= $block->escapeHtml(__('B Negative')) ?></option>
                            <option value="O+"><?= $block->escapeHtml(__('O Positive')) ?></option>
                            <option value="O-"><?= $block->escapeHtml(__('O Negative')) ?></option>
                            <option value="AB+"><?= $block->escapeHtml(__('AB Positive')) ?></option>
                            <option value="AB-"><?= $block->escapeHtml(__('AB Negative')) ?></option>
                            <option value="unknown"><?= $block->escapeHtml(__('Unknown')) ?></option>
                        </select>
                        <div class="patient-form-error-message" id="blood-group-patient-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field telephone required">
                    <label for="telephone" class="label telephone patient-form-label">
                        <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
                        <span class="required-asterisk">*</span>
                    </label>
                    <div class="control patient-input">
                        <input name="telephone" id="addtelephone" maxlength="10" placeholder="+91" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="patient-input-text" type="tel" pattern="[0-9]{10}" required />
                        <div id="telephone-patient-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field whatsapp required">
                    <label class="label whatsapp patient-form-label" for="whatsapp">
                        <span><?= $block->escapeHtml(__('WhatsApp Number')) ?></span><span class="required-asterisk">*</span>
                    </label>
                    <div class="control patient-input">
                        <input name="whatsapp" id="addwhatsapp" maxlength="10" placeholder="+91" title="<?= $block->escapeHtmlAttr(__('WhatsApp Number')) ?>" class="patient-input-text" type="tel" pattern="[0-9]{10}" required />
                        <div id="whatsapp-patient-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                <span class="same-as-phone">
                    <input type="checkbox" id="sameAsPhone" style="width: 14px; height: 14px" />
                    <small style="font-weight: lighter; font-size: 14px;"><?= $block->escapeHtml(__('Make sure the Phone Number and WhatsApp Number are the same.')) ?></small>
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field house_no required">
                    <label class="label house_no patient-form-label" for="house_no"><span><?= $block->escapeHtml(__('Flat,House No')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="house_no" id="addhouse_no" title="<?= $block->escapeHtmlAttr(__('Flat,House No*')) ?>" class="patient-input-text" type="text" pattern="^[a-zA-Z]{4,}(?: [a-zA-Z]+){0,2}$" required />
                        <div id="house-patient-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field street required">
                    <label class="label street patient-form-label" for="street"><span><?= $block->escapeHtml(__('Street')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="street" id="addstreet" title="<?= $block->escapeHtmlAttr(__('Street')) ?>" class="patient-input-text" type="text" pattern="^[a-zA-Z]{4,}(?: [a-zA-Z]+){0,2}$" required />
                        <div id="street-patient-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field area required">
                    <label class="label area patient-form-label" for="area"><span><?= $block->escapeHtml(__('Area')) ?></span></label>
                    <div class="control patient-input">
                        <input name="area" id="addarea" title="<?= $block->escapeHtmlAttr(__('Area')) ?>" class="patient-input-text" type="text" pattern="^[a-zA-Z]{4,}(?: [a-zA-Z]+){0,2}$" />
                        <div id="area-patient-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field city required">
                    <label class="label city patient-form-label" for="city"><span><?= $block->escapeHtml(__('City')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="city" id="addcity" title="<?= $block->escapeHtmlAttr(__('City')) ?>" class="patient-input-text" type="text" value="Chennai" readonly pattern="^[a-zA-Z]+(?:[\s-][a-zA-Z]+)*$" required />
                        <div id="city-patient-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field region required">
                    <label class="label region patient-form-label" for="region_id"><span><?= $block->escapeHtml(__('State')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <select name="region_id" id="addregion_id" class="patient-input-text" required>
                            <option value="533">Andaman and Nicobar Islands</option>
                            <option value="534">Andhra Pradesh</option>
                            <option value="535">Arunachal Pradesh</option>
                            <option value="536">Assam</option>
                            <option value="537">Bihar</option>
                            <option value="538">Chandigarh</option>
                            <option value="539">Chhattisgarh</option>
                            <option value="540">Dadra and Nagar Haveli</option>
                            <option value="541">Daman and Diu</option>
                            <option value="542">Delhi</option>
                            <option value="543">Goa</option>
                            <option value="544">Gujarat</option>
                            <option value="545">Haryana</option>
                            <option value="546">Himachal Pradesh</option>
                            <option value="547">Jammu and Kashmir</option>
                            <option value="548">Jharkhand</option>
                            <option value="549">Karnataka</option>
                            <option value="550">Kerala</option>
                            <option value="551">Lakshadweep</option>
                            <option value="552">Madhya Pradesh</option>
                            <option value="553">Maharashtra</option>
                            <option value="554">Manipur</option>
                            <option value="555">Meghalaya</option>
                            <option value="556">Mizoram</option>
                            <option value="557">Nagaland</option>
                            <option value="558">Odisha</option>
                            <option value="559">Puducherry</option>
                            <option value="560">Punjab</option>
                            <option value="561">Rajasthan</option>
                            <option value="562">Sikkim</option>
                            <option value="563" selected>Tamil Nadu</option>
                            <option value="564">Telangana</option>
                            <option value="565">Tripura</option>
                            <option value="566">Uttar Pradesh</option>
                            <option value="567">Uttarakhand</option>
                            <option value="568">West Bengal</option>
                        </select>
                        <input name="region" value="Tamil Nadu" id="addregion" class="input-text" type="text" title="State" style="display: none;" required />
                        <div id="region-error-message" class="patient-form-error-message" style="color: red; display: none;"></div>
                        <script>
                            document.addEventListener('DOMContentLoaded', function() {
                                let regionSelect = document.getElementById('addregion_id');
                                let regionInput = document.getElementById('addregion');
                                let errorMessage = document.getElementById('region-error-message');

                                regionSelect.addEventListener('change', function() {
                                    if (regionSelect.value !== "563") {
                                        regionSelect.vlaue = "563";
                                        regionInput.value = "Tamil Nadu";
                                        errorMessage.textContent = "We only serve for Tamil Nadu location as of now.";
                                        errorMessage.style.display = "block";
                                    } else {
                                        errorMessage.style.display = "none";
                                    }
                                });
                                regionInput.value = "Tamil Nadu";
                            });
                        </script>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field pincode required">
                    <label class="label pincode patient-form-label" for="pincode"><span><?= $block->escapeHtml(__('Pincode')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="pincode" id="addpincode" title="<?= $block->escapeHtmlAttr(__('Pincode')) ?>" class="patient-input-text" type="text" pattern="[0-9]{6}" required />
                        <div id="pincode-patient-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="field country_id required" style="display: none;">
            <label class="label country_id patient-form-label" for="country_id"></label>
            <div class="control patient-input">
                <input name="country_id" id="addcountry_id" value="IN" class="input-text" type="text" required />
            </div>
        </div>
        <div class="primary">
            <button type="submit" class="action submit primary" id="patient-submit-btn" style="margin-top: 10px; margin-left: 25%" disabled>Add Patient</button>
        </div>
    </div>
</div>

<div id="edit-modal-content" style="display: none;">
    <div class="container patient-addr" id="edit-patient-addr1">
        <div class="edit-patient-label-page">
            <label class="patient-label"><?= $block->escapeHtml(__('Edit Patient Details')) ?></label>
        </div>
        <div class="field edit_patient_id required" style="display: none;">
            <label class="label edit_patient_id patient-form-label" for="patient_id"><span><?= $block->escapeHtml(__('Patient ID*')) ?></span></label>
            <div class="control patient-input">
                <input name="patient_id" id="edit-patient-id" class="input-text" type="hidden" required />
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field firstname required">
                    <label class="label firstname patient-form-label" for="firstname"><span><?= $block->escapeHtml(__('First Name')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="firstname" id="edit-firstname" placeholder="Enter your first name" title="<?= $block->escapeHtmlAttr(__('First Name')) ?>" class="patient-input-text" type="text" pattern="^[a-zA-Z]{2,}$" required />
                        <div class="patient-form-error-message" id="edit-firstname-error-message"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field lastname required">
                    <label class="label lastname patient-form-label" for="lastname"><span><?= $block->escapeHtml(__('Last Name')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="lastname" id="edit-lastname" placeholder="Enter your last name" title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>" class="patient-input-text" type="text" pattern="^[a-zA-Z]{2,}$" required />
                        <div class="patient-form-error-message" id="edit-lastname-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field customer_email required">
                    <label class="label customer_email patient-form-label" for="customer_email"><span><?= $block->escapeHtml(__('Email ID')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="customer_email" id="edit-email" placeholder="Enter valid Email Address" title="<?= $block->escapeHtmlAttr(__('Email ID')) ?>" class="patient-input-text" type="email" pattern="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}" required />
                        <div class="patient-form-error-message" id="edit-email-error-message"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field customer_gender required">
                    <label for="customer_gender" class="label customer_gender patient-form-label"><span><?= $block->escapeHtml(__('Gender')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <select name="customer_gender" id="edit-gender" title="<?= $block->escapeHtmlAttr(__('Gender')) ?>" class="patient-input-text" required>
                            <option value="" selected disabled><?= $block->escapeHtmlAttr(__('Select Gender')) ?></option>
                            <option value="male"><?= $block->escapeHtml(__('Male')) ?></option>
                            <option value="female"><?= $block->escapeHtml(__('Female')) ?></option>
                            <option value="transgender"><?= $block->escapeHtml(__('Transgender')) ?></option>
                        </select>
                        <div class="patient-form-error-message" id="edit-gender-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field dob required">
                    <label for="dob" class="label dob patient-form-label"><span><?= $block->escapeHtml(__('Date of Birth')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input" style="position: relative;">
                        <input name="dob" id="edit-dob" title="<?= $block->escapeHtmlAttr(__('Date of Birth')) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Select Date of Birth')) ?>" class="patient-input-text" type="text" required style="padding-right: 40px;" />
                        <div class="patient-form-error-message" id="edit-dob-error-message"></div>
                        <span class="calendar-icon" style="position: absolute; right: 10px; top: 45%; transform: translateY(-50%); cursor: pointer;">
                            <img src="<?= $block->getViewFileUrl('MedizinhubCore_Patient::images/calendar-date.svg') ?>" alt="Calendar Icon" style="width: 20px; height: 20px;">
                        </span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field blood_group required">
                    <label class="label blood_group patient-form-label" for="blood_group"><span><?= $block->escapeHtml(__('Blood Group')) ?></span></label>
                    <div class="control patient-input">
                        <select name="blood_group" id="edit-blood_group" title="<?= $block->escapeHtmlAttr(__('Blood Group')) ?>" class="patient-input-text" required>
                            <option value="" selected disabled><?= $block->escapeHtml(__('Select Blood Group')) ?></option>
                            <option value="A+"><?= $block->escapeHtml(__('A Positive')) ?></option>
                            <option value="A-"><?= $block->escapeHtml(__('A Negative')) ?></option>
                            <option value="B+"><?= $block->escapeHtml(__('B Positive')) ?></option>
                            <option value="B-"><?= $block->escapeHtml(__('B Negative')) ?></option>
                            <option value="O+"><?= $block->escapeHtml(__('O Positive')) ?></option>
                            <option value="O-"><?= $block->escapeHtml(__('O Negative')) ?></option>
                            <option value="AB+"><?= $block->escapeHtml(__('AB Positive')) ?></option>
                            <option value="AB-"><?= $block->escapeHtml(__('AB Negative')) ?></option>
                            <option value="unknown"><?= $block->escapeHtml(__('Unknown')) ?></option>
                        </select>
                        <div class="patient-form-error-message" id="edit-blood-group-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field telephone required">
                    <label for="telephone" class="label telephone patient-form-label">
                        <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
                        <span class="required-asterisk">*</span>
                    </label>
                    <div class="control patient-input">
                        <input name="telephone" id="edit-telephone" placeholder="+91" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="patient-input-text" type="tel" pattern="[0-9]{10}" required />
                        <div id="edit-telephone-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field whatsapp required">
                    <label class="label whatsapp patient-form-label" for="whatsapp">
                        <span><?= $block->escapeHtml(__('WhatsApp Number')) ?></span><span class="required-asterisk">*</span>
                    </label>
                    <div class="control patient-input">
                        <input name="whatsapp" id="edit-whatsapp" placeholder="+91" title="<?= $block->escapeHtmlAttr(__('WhatsApp Number')) ?>" class="patient-input-text" type="tel" pattern="[0-9]{10}" required />
                        <div id="edit-whatsapp-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                <span class="same-as-phone">
                    <input type="checkbox" id="sameAsPhone" style="width: 14px; height: 14px" />
                    <small style="font-weight: lighter; font-size: 14px;"><?= $block->escapeHtml(__('Make sure the Phone Number and WhatsApp Number are the same.')) ?></small>
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field house_no required">
                    <label class="label house_no patient-form-label" for="house_no"><span><?= $block->escapeHtml(__('Flat,House No')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="house_no" id="edit-house_no" title="<?= $block->escapeHtmlAttr(__('Flat,House No*')) ?>" class="patient-input-text" type="text" pattern="^[a-zA-Z]{4,}(?: [a-zA-Z]+){0,2}$" required />
                        <div id="edit-house-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field street required">
                    <label class="label street patient-form-label" for="street"><span><?= $block->escapeHtml(__('Street')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="street" id="edit-street" title="<?= $block->escapeHtmlAttr(__('Street')) ?>" class="patient-input-text" type="text" pattern="^[a-zA-Z]{4,}(?: [a-zA-Z]+){0,2}$" required />
                        <div id="edit-street-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field area required">
                    <label class="label area patient-form-label" for="area"><span><?= $block->escapeHtml(__('Area')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="area" id="edit-area" title="<?= $block->escapeHtmlAttr(__('Area')) ?>" class="patient-input-text" type="text" pattern="^[a-zA-Z]{4,}(?: [a-zA-Z]+){0,2}$" required />
                        <div id="edit-area-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field city required">
                    <label class="label city patient-form-label" for="city"><span><?= $block->escapeHtml(__('City')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="city" id="edit-city" title="<?= $block->escapeHtmlAttr(__('City')) ?>" class="patient-input-text" type="text" value="Chennai" readonly pattern="^[a-zA-Z]+(?:[\s-][a-zA-Z]+)*$" required />
                        <div id="edit-city-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field region required">
                    <label class="label region patient-form-label" for="region_id"><span><?= $block->escapeHtml(__('State')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <select name="region_id" id="edit-region_id" class="patient-input-text" required>
                            <option value="533">Andaman and Nicobar Islands</option>
                            <option value="534">Andhra Pradesh</option>
                            <option value="535">Arunachal Pradesh</option>
                            <option value="536">Assam</option>
                            <option value="537">Bihar</option>
                            <option value="538">Chandigarh</option>
                            <option value="539">Chhattisgarh</option>
                            <option value="540">Dadra and Nagar Haveli</option>
                            <option value="541">Daman and Diu</option>
                            <option value="542">Delhi</option>
                            <option value="543">Goa</option>
                            <option value="544">Gujarat</option>
                            <option value="545">Haryana</option>
                            <option value="546">Himachal Pradesh</option>
                            <option value="547">Jammu and Kashmir</option>
                            <option value="548">Jharkhand</option>
                            <option value="549">Karnataka</option>
                            <option value="550">Kerala</option>
                            <option value="551">Lakshadweep</option>
                            <option value="552">Madhya Pradesh</option>
                            <option value="553">Maharashtra</option>
                            <option value="554">Manipur</option>
                            <option value="555">Meghalaya</option>
                            <option value="556">Mizoram</option>
                            <option value="557">Nagaland</option>
                            <option value="558">Odisha</option>
                            <option value="559">Puducherry</option>
                            <option value="560">Punjab</option>
                            <option value="561">Rajasthan</option>
                            <option value="562">Sikkim</option>
                            <option value="563" selected>Tamil Nadu</option>
                            <option value="564">Telangana</option>
                            <option value="565">Tripura</option>
                            <option value="566">Uttar Pradesh</option>
                            <option value="567">Uttarakhand</option>
                            <option value="568">West Bengal</option>
                        </select>
                        <input name="region" value="Tamil Nadu" id="edit-region" class="input-text" type="text" title="State" style="display: none;" required />
                        <div class="patient-form-error-message" id="edit-region-error-message" style="color: red; display: none;"></div>
                        <script>
                            document.addEventListener('DOMContentLoaded', function() {
                                let editRegionSelect = document.getElementById('edit-region_id');
                                let editRegionInput = document.getElementById('edit-region');
                                let editErrorMessage = document.getElementById('edit-region-error-message');

                                editRegionSelect.addEventListener('change', function() {
                                    if (editRegionSelect.value !== "563") {
                                        editRegionSelect.value = "563";
                                        editRegionInput.value = "Tamil Nadu";
                                        editErrorMessage.textContent = "We only serve for Tamil Nadu location as of now.";
                                        editErrorMessage.style.display = "block";
                                    } else {
                                        errorMessage.style.display = "none";
                                    }
                                });
                                editRegionInput.value = "Tamil Nadu";
                            });
                        </script>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <div class="field pincode required">
                    <label class="label pincode patient-form-label" for="pincode"><span><?= $block->escapeHtml(__('Pincode')) ?></span><span class="required-asterisk">*</span></label>
                    <div class="control patient-input">
                        <input name="pincode" id="edit-pincode" title="<?= $block->escapeHtmlAttr(__('Pincode')) ?>" class="patient-input-text" type="text" pattern="[0-9]{6}" required />
                        <div id="edit-pincode-error-message" class="patient-form-error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="field country_id required" style="display: none;">
            <label class="label country_id patient-form-label" for="country_id"></label>
            <div class="control patient-input">
                <input name="country_id" value="IN" class="input-text" type="text" required />
            </div>
        </div>
        <div class="primary">
            <button type="submit" class="action submit primary" id="patient-edit-btn" style="margin-top: 10px;">Update Patient</button>
            <button class="go-back-btn" id="go-back">Cancel</button>
        </div>
    </div>
</div>

<div id="deleteModal" class="deleteModal" style="display: none;">
    <div class="modal-content delete-popup-content">
        <span class="modal-title">Delete Address</span>
        <p>Are you sure you want to delete this Patient Details?</p>
        <div class="btn-outer">
            <button id="cancelButton" class="btn-cancel">Cancel</button>
            <button id="confirmDeleteButton" class="btn-delete">Delete</button>
        </div>
    </div>
</div>

<div id="successModal" class="successModal" style="display: none;">
    <div class="success-popup-content">
        <img src="<?= $block->getViewFileUrl('MedizinhubCore_Patient::images/success-response-image.svg'); ?>" alt="Success Image">
        <br>
        <span class="modal-title">Your Appointment is Confirmed!</span>
        <p>Our Team will call shortly for consultation, For more info call <strong>90476 60909</strong></p>
        <button id="go-home">Continue Shopping</button>
    </div>
</div>
