<div style="padding: 0 0 40px 0;" class="doctor-consult">
    <div class="container">
        <div style="padding: 0 65px;" class="row">
            <p style="color: #063851;font-family: Source Sans Pro,Sans-serif;font-size: 24px;font-weight: 600;">Consult by category</p>
            <p style="color: #859ca8;font-family: Ubuntu,Sans-serif;font-size: 18px;font-weight: 400;">Book a Doctor Consultation Online for Expert Advice, Diagnosis, and Personalized Treatment From the Comfort of Your Home <span><img class="subheading_logo" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/stars.png'); ?>" /></span></p>
            <div class="row g-3 justify-content-center">
            <div class="col-6 col-md-4 col-lg-2 text-center">
                <a href="/consult-option" class="text-decoration-none" title="General Physician">
                    <div class="consult-img">
                        <img class="img-fluid mb-2" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/doctor_1.png'); ?>" alt="General Physician">
                        <p class="text-dark fw-semibold consult-page-title">General Physician</p>
                    </div>
                </a>
            </div>
            <div class="col-6 col-md-4 col-lg-2 text-center">
                <a href="/consult-option" class="text-decoration-none" title="ENT Consult">
                    <div class="consult-img">
                        <img class="img-fluid mb-2" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/doctor_2.png'); ?>" alt="ENT Consult">
                        <p class="text-dark fw-semibold consult-page-title">ENT Consult</p>
                    </div>
                </a>
            </div>
            <div class="col-6 col-md-4 col-lg-2 text-center">
                <a href="/consult-option" class="text-decoration-none" title="General Surgeon">
                    <div class="consult-img">
                        <img class="img-fluid mb-2" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/doctor_3.png'); ?>" alt="General Surgeon">
                        <p class="text-dark fw-semibold consult-page-title">General Surgeon</p>
                    </div>
                </a>
            </div>
            <div class="col-6 col-md-4 col-lg-2 text-center">
                <a href="/consult-option" class="text-decoration-none" title="Physiotherapist">
                    <div class="consult-img">
                        <img class="img-fluid mb-2" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/doctor_4.png'); ?>" alt="Physiotherapist">
                        <p class="text-dark fw-semibold consult-page-title">Physiotherapist</p>
                    </div>
                </a>
            </div>
            <div class="col-6 col-md-4 col-lg-2 text-center">
                <a href="/consult-option" class="text-decoration-none" title="Orthopedics Consult">
                    <div class="consult-img">
                        <img class="img-fluid mb-2" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/doctor_5.png'); ?>" alt="Orthopedics Consult">
                        <p class="text-dark fw-semibold consult-page-title">Orthopedics Consult</p>
                    </div>
                </a>
            </div>
        </div>
        </div>
    </div>
</div>
<div class="mobile_qr">
    <a href="https://play.google.com/store/apps/details?id=com.mhb.medizin_hub" target="_blank">
        <img src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/mobile_qr.png'); ?>" alt="MedizinHub Mobile App"  title="MedizinHub Mobile App" class="mobile_qr_img">
    </a>
</div>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> -->


<style>
    .consult-img{
        width: 100%;
        text-align: center;
    }
    main{
        display: none !important;
    }
    .page-title-wrapper{
        display: none;
    }
.consult-page-title{
        text-decoration:none;font-size: 16px;font-weight:600;font-family:Source Sans Pro;color:#000;
    }
</style>
<script>

    document.addEventListener('DOMContentLoaded', function() {

        const consultantLinks = document.querySelectorAll('.consultant-link');

        consultantLinks.forEach(link => {

            link.addEventListener('click', function(e) {

                const consultantType = this.getAttribute('data-consultant-type');

                sessionStorage.setItem('selectedConsultantType', consultantType);

            });

        });

    });


</script>
