<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\Sales\Block\Order\Items $block */
?>
<style>

    .table-order-items th, .table-order-items td {
    padding: 8px !important;
    text-align: right !important;
}

</style>
<div class="table-wrapper order-items">
    <table class="data table table-order-items" id="my-orders-table" summary="<?= $block->escapeHtml(__('Items Ordered')) ?>">
        <caption class="table-caption"><?= $block->escapeHtml(__('Items Ordered')) ?></caption>
        <thead>
            <?php if ($block->isPagerDisplayed()) : ?>
                <tr>
                    <td colspan="5" data-block="order-items-pager-top" class="order-pager-wrapper order-pager-wrapper-top">
                        <?= $block->getPagerHtml() ?>
                    </td>
                </tr>
            <?php endif; ?>
            <tr>
                <th class="col name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                <th class="col batch-id"><?= $block->escapeHtml(__('Batch ID')) ?></th>
                <th class="col expiry"><?= $block->escapeHtml(__('Expiry Date')) ?></th>
                <th class="col price"><?= $block->escapeHtml(__('Price')) ?></th>
                <th class="col qty"><?= $block->escapeHtml(__('Qty')) ?></th>
                <th class="col subtotal"><?= $block->escapeHtml(__('Subtotal')) ?></th>
            </tr>
        </thead>
        <tbody>
        <?php
        $items = $block->getItems();
        $giftMessage = '';

        // Get the Object Manager
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
        $connection = $resource->getConnection();
        $tableName = $resource->getTableName('snowdog_custom_description');

        /** @var \Magento\Framework\Pricing\Helper\Data $priceHelper */
        $priceHelper = $objectManager->get(\Magento\Framework\Pricing\Helper\Data::class);

        ?>
        <?php foreach ($items as $item) :
            if ($item->getParentItem()) :
                continue;
            endif;

            $productId = $item->getProductId();
            $select = $connection->select()
                ->from($tableName, ['title'])
                ->where('product_id = ?', (int)$productId)
                ->where('expiry_status = ?', 1);
            $ExpirySelection = $connection->select()
                ->from($tableName, ['expiry_date'])
                ->where('product_id = ?', (int)$productId)
                ->where('expiry_status = ?', 1);
            $batchId = $connection->fetchOne($select);
            $ExpiryDate = $connection->fetchOne($ExpirySelection);
            $ExpiryDate = $ExpiryDate ?: __('N/A');
            $batchId = $batchId ?: __('N/A');
            ?>
            <tr>
                <td data-label="<?= $block->escapeHtml(__('Product Name')) ?>"><?= $block->escapeHtml($item->getName()) ?></td> <!-- Display Product Name -->
                <td data-label="<?= $block->escapeHtml(__('Batch ID')) ?>"><?= $block->escapeHtml($batchId) ?></td>
                <td data-label="<?= $block->escapeHtml(__('Expiry Date')) ?>"><?= $block->escapeHtml($ExpiryDate) ?></td>
                <td data-label="<?= $block->escapeHtml(__('Price')) ?>"><?= $priceHelper->currency($item->getPrice(), true, false) ?></td> <!-- Display Price -->
                <td data-label="<?= $block->escapeHtml(__('Qty')) ?>"><?= $block->escapeHtml($item->getQtyOrdered()) ?></td> <!-- Display Qty -->
                <td data-label="<?= $block->escapeHtml(__('Subtotal')) ?>"><?= $priceHelper->currency($item->getRowTotal(), true, false) ?></td> <!-- Display Subtotal -->
            </tr>
            <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)->isMessagesAllowed('order_item', $item) && $item->getGiftMessageId()) : ?>
                <?php $giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)->getGiftMessageForEntity($item); ?>
                <tr>
                    <td class="col options" colspan="5">
                        <a href="#"
                           id="order-item-gift-message-link-<?= (int) $item->getId() ?>"
                           class="action show"
                           aria-controls="order-item-gift-message-<?= (int) $item->getId() ?>"
                           data-item-id="<?= (int) $item->getId() ?>">
                            <?= $block->escapeHtml(__('Gift Message')) ?>
                        </a>
                        <div class="order-gift-message" id="order-item-gift-message-<?= (int) $item->getId() ?>" role="region" aria-expanded="false" tabindex="-1">
                            <a href="#"
                               title="<?= $block->escapeHtml(__('Close')) ?>"
                               aria-controls="order-item-gift-message-<?= (int) $item->getId() ?>"
                               data-item-id="<?= (int) $item->getId() ?>"
                               class="action close">
                                <?= $block->escapeHtml(__('Close')) ?>
                            </a>
                            <dl class="item-options">
                                <dt class="item-sender"><strong class="label"><?= $block->escapeHtml(__('From')) ?></strong><?= $block->escapeHtml($giftMessage->getSender()) ?></dt>
                                <dt class="item-recipient"><strong class="label"><?= $block->escapeHtml(__('To')) ?></strong><?= $block->escapeHtml($giftMessage->getRecipient()) ?></dt>
                                <dd class="item-message"><?= /* @noEscape */ $this->helper(\Magento\GiftMessage\Helper\Message::class)->getEscapedGiftMessage($item) ?></dd>
                            </dl>
                        </div>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
        <tfoot>
            <?php if ($block->isPagerDisplayed()) : ?>
                <tr>
                    <td colspan="5" data-block="order-items-pager-bottom" class="order-pager-wrapper order-pager-wrapper-bottom">
                        <?= $block->getPagerHtml() ?>
                    </td>
                </tr>
            <?php endif; ?>
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
</div>
<?php if ($giftMessage) : ?>
<script type="text/x-magento-init">
    {
        "a.action.show, a.action.close": {
            "giftMessage": {}
        }
    }
</script>
<?php endif; ?>
