<style>
.editorial-steps {
    text-align: center;
}

.doctor-details{
    margin: 30px;
    text-align: center;
}
.content-creation-steps{
    margin: 20px 0;
    text-align: center;
}
.content-creation {
    background: #D7FBD0;
    padding-top: 20px;
    border-radius: 10px;
}
/* .editorial-details {
    margin-top: 20px;
} */
.editorial-details h1{
    margin-bottom: 12px !important;
} 
.content-help-text{ 
    margin-bottom: 24px !important; 
}
.editorial-banner {
    margin-bottom: 32px;
}
.editorial-description, 
.editorial-description ol li,
.editorial-description ul li,
.editorial-content ol li,
.editorial-content ul li {
    color: #000;
    font-family: "Source Sans Pro";
    font-size: 16px;
    font-weight: 400;
    line-height: 26px;
    letter-spacing: 0.48px;
    /* margin-bottom: 32px; */
}
.content-creation-steps .editorial-description{
    padding: 0 30px;
}
.editorial-title {
    color: #063851;
    font-family: "Source Sans Pro";
    font-size: 22px;
    font-weight: 600;
}
.editorial-help-text,
.content-help-text {
    color: #063851;
    font-family: "Source Sans Pro";
    font-size: 20px;
    font-weight: 600;
}
.page-title {
    display: none !important;
}
.breadcrumbs {
    color: #036C58;
    font-family: 'Ubuntu';
    font-size: 16px;
    font-weight: 500;
}
.breadcrumb-name { 
    color: #6E7F87;
    font-family: 'Ubuntu';
    font-size: 16px;
    font-weight: 400;
}
</style>
<div class="editorial-content">
        <div class="breadcrumbs">Home <Span class="breadcrumb-name">> Editorial Policy</span></div>
        <div class="editorial-banner">
                <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-policy.svg'); ?>" alt="MedizinHub Editorial Policy">
        </div>
        <div class="editorial-details">
                <h1 class="editorial-title">MedizinHub Editorial Policy!</h1>
                <p class="editorial-description">At Medizinhub, we are committed to providing our customers with accurate, transparent, and reliable information related to health, wellness, and medical products. Our editorial policy is designed to ensure the highest quality content that aligns with industry standards, customer needs, and ethical guidelines. This policy outlines how we create, review, and maintain all content on our platform to foster trust and offer valuable information to our users.</p>
                <h1 class="editorial-title">Editorial Workflow</h1>
                <p class="editorial-description">Our editorial workflow follows a structured process to ensure that all content, from product descriptions to health articles, adheres to the highest standards of accuracy and integrity.</p>
        </div>
        <div class="editorial-content container">
                <div class="row">
                        <div class="col-md-2 editorial-steps">
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-step1.svg'); ?>" alt="Step 1"><br>
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-step-line.svg'); ?>">
                        </div>

                        <div class="col-md-10 editorial-details">
                        <h3 class="content-help-text">Content Planning:</h3>
                        <!-- <p class="editorial-description"> -->
                                <ul>
                                        <li><strong>Objective Setting: </strong>Define the purpose of the content (e.g., educating users on health topics, promoting products, or providing healthcare advice).</li>
                                        <li><strong>Topic Research: </strong>Identify relevant health or medical topics, product categories, or services that the audience will benefit from.</li>
                                        <li><strong>SEO Optimization: </strong>Choose keywords that match healthcare or product trends to improve visibility in search engines.</li>
                                </ul>
                        <!-- </p> -->
                        </div>
                </div>
                <div class="row">
                        <div class="col-md-2 editorial-steps">
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-step2.svg'); ?>" alt="Step 1"><br>
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-step-line.svg'); ?>">
                        </div>

                        <div class="col-md-10 editorial-details">
                        <h3 class="content-help-text">Content Creation:</h3>
                        <!-- <p class="editorial-description"> -->
                                <ul>
                                        <li><strong>Writing: </strong>Writers create well-researched, accurate, and original content about medicines, health advice, or product details.</li>
                                        <li><strong>Fact-Checking: </strong>Ensure that all medical information is accurate, sourced from reliable medical journals, and adheres to legal requirements.</li>
                                        <li><strong>Compliance: </strong>Verify that the content complies with healthcare regulations (such as FDA rules) and advertising guidelines for pharmaceutical products.</li>
                                </ul>
                        <!-- </p> -->
                        </div>
                </div>
                <div class="row">
                        <div class="col-md-2 editorial-steps">
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-step3.svg'); ?>" alt="Step 1"><br>
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-step-line.svg'); ?>">
                        </div>

                        <div class="col-md-10 editorial-details">
                        <h3 class="content-help-text">Editing and Review:</h3>
                        <!-- <p class="editorial-description"> -->
                                <ul>
                                        <li><strong>Initial Edit: </strong>Editors review the content for grammar, clarity, and tone. Ensure the content is accessible to a wide audience, especially for medical terms.</li>
                                        <li><strong>Medical Review: </strong>A healthcare professional or medical reviewer verifies the accuracy and appropriateness of the health-related content.</li>
                                        <li><strong>SEO Review: </strong>Check if the content is optimized for search engines (meta descriptions, tags, etc.) while maintaining readability.</li>
                                </ul>
                        <!-- </p> -->
                        </div>
                </div>
                <div class="row">
                        <div class="col-md-2 editorial-steps">
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-step4.svg'); ?>" alt="Step 1"><br>
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-step-line.svg'); ?>">
                        </div>

                        <div class="col-md-10 editorial-details">
                        <h3 class="content-help-text">Approval:</h3>
                        <!-- <p class="editorial-description"> -->
                                <ul>
                                        <li><strong>Editorial Approval: </strong>The content is approved by the editorial team after ensuring it meets quality standards.</li>
                                        <li><strong>Legal Approval: </strong>For any health claims, product endorsements, or medical advice, get approval from legal experts to ensure regulatory compliance.</li>
                                </ul>
                        <!-- </p> -->
                        </div>
                </div>
                <div class="row">
                        <div class="col-md-2 editorial-steps">
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-step5.svg'); ?>" alt="Step 1"><br>
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-step-line.svg'); ?>">
                        </div>

                        <div class="col-md-10 editorial-details">
                        <h3 class="content-help-text">Publishing:</h3>
                        <!-- <p class="editorial-description"> -->
                                <ul>
                                        <li><strong>Formatting: </strong>The content is formatted for web pages, including images, headings, and links to products or related articles.</li>
                                        <li><strong>CMS Upload: </strong>The content is uploaded to the website's Content Management System (CMS) and prepared for publishing.</li>
                                        <li><strong>Scheduling: </strong>Content is scheduled for release based on a calendar, ensuring a consistent flow of updates.</li>
                                </ul>
                        <!-- </p> -->
                        </div>
                </div>
                <div class="row">
                        <div class="col-md-2 editorial-steps">
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-step6.svg'); ?>" alt="Step 1"><br>
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-step-line.svg'); ?>">
                        </div>

                        <div class="col-md-10 editorial-details">
                        <h3 class="content-help-text">Post-Publication Monitoring:</h3>
                        <!-- <p class="editorial-description"> -->
                                <ul>
                                        <li><strong>User Feedback: </strong>Monitor user interactions, comments, and feedback to gauge the content’s effectiveness and engagement.</li>
                                        <li><strong>Analytics Review: </strong>Track the performance of the content through analytics (clicks, views, sales) to refine future content strategies.</li>
                                </ul>
                        <!-- </p> -->
                        </div>
                </div>
                <div class="row">
                        <div class="col-md-2 editorial-steps">
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/editorial-step7.svg'); ?>" alt="Step 1">
                        </div>

                        <div class="col-md-10 editorial-details">
                        <h3 class="content-help-text">Updating and Maintenance:</h3>
                        <!-- <p class="editorial-description"> -->
                                <ul>
                                        <li><strong>Regular Reviews: </strong>Health-related content should be updated regularly to reflect new research, product updates, or changes in medical guidelines.</li>
                                        <li><strong>Corrections: </strong>If any errors are identified, implement corrections promptly and transparently.</li>
                                </ul>
                        <!-- </p> -->
                </div>
                </div>
        </div>
        <!-- <div class="editorial-content">
                <h2 class="editorial-title">Framework for Content Creation</h2>
                <p class="editorial-description">At Medizinehub, we strive to create content that is informative, helpful, and easy to understand. Our content creation framework is based on the following principles:</p>
                <ul>
                        <li><strong>Accuracy and Transparency: </strong>Our content is based on verified information, ensuring that customers have access to accurate health and product details. We avoid making unsubstantiated claims and ensure transparency about product efficacy, safety, and usage.</li>
                        <li><strong>User-Centered Approach: </strong>All content is created with our customers in mind. We prioritize user-friendly language and formats that make it easy for users to find the information they need and understand it, even if they are not medically trained.</li>
                        <li><strong>SEO and Readability: </strong>We optimize content for search engines to improve visibility while maintaining readability and clarity for our audience.</li>
                        <li><strong>Diversity and Inclusivity: </strong>Our content is designed to cater to a diverse range of users, including people from different backgrounds and with varying health needs.</li>
                        <li><strong>Ethical Responsibility: </strong>Medizinhub adheres to ethical content creation by providing unbiased information. We do not promote products based on commercial interests but focus on what is best for our users' health and wellbeing.</li>
                </ul>
        </div> -->

        <div class="editorial-content container">
                <h2 class="editorial-title">Framework for Content Creation</h2>
                <p class="editorial-description">
                        At Medizinehub, we strive to create content that is informative, helpful, and easy to understand. Our content creation framework is based on the following principles:
                </p>
                <div class="row content-creation">
                        <div class="col-md-4 content-creation-steps">
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/authentic.svg'); ?>" alt="Authentic">
                        <h2 class="editorial-help-text">Authentic</h2>
                        <p class="editorial-description">
                                Medical content is thoroughly researched and verified, ensuring accuracy and reliability from trusted sources.
                        </p>
                        </div>
                        <div class="col-md-4 content-creation-steps">
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/credible.svg'); ?>" alt="Credible">
                        <h2 class="editorial-help-text">Credible</h2>
                        <p class="editorial-description">
                                All facts are verified by healthcare professionals to ensure accuracy and journalistic integrity.
                        </p>
                        </div>
                        <div class="col-md-4 content-creation-steps">
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/user-focused.svg'); ?>" alt="User Focused">
                        <h2 class="editorial-help-text">User-Focused</h2>
                        <p class="editorial-description">
                                Content is designed to meet user needs, offering clear, relevant, and educational health information.
                        </p>
                        </div>
                        <div class="col-md-4 content-creation-steps">
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/authoritative.svg'); ?>" alt="Authoritative">
                        <h2 class="editorial-help-text">Authoritative</h2>
                        <p class="editorial-description">
                        We credit authors' credentials and cite reliable sources, ensuring our content is backed by experts and based on trusted, authoritative references.
                        </p>
                        </div>
                        <div class="col-md-4 content-creation-steps">
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/contemporary.svg'); ?>" alt="Contemporary">
                        <h2 class="editorial-help-text">Contemporary</h2>
                        <p class="editorial-description">
                        We regularly update content to reflect the latest medical research and trends, ensuring users receive the most current and accurate information available.
                        </p>
                        </div>
                        <div class="col-md-4 content-creation-steps">
                        <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/unbiased.svg'); ?>" alt="Unbiased">
                        <h2 class="editorial-help-text">Unbiased</h2>
                        <p class="editorial-description">
                                Our content remains impartial, providing factual, non-promotional information while respecting copyright and confidentiality laws.
                        </p>
                        </div>
                </div>
        </div>


        <div class="editorial-content container">
                <h2 class="editorial-title">Our Expert Doctors</h2>
                <p class="editorial-description">At Medizinhub, our expert team of experienced doctors and healthcare professionals ensures that every piece of content is accurate, reliable, and relevant. Each specialist brings their expertise to review and create content, providing trustworthy information that empowers our users to make informed decisions about their health and well-being.</p>
                <div class="row editorial-background">
                       <div class="col-md-3">
                            <div class="doctor-details">
                            <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/doctor-image1.svg'); ?>" alt="Doctor1">
                            <h2 class="editorial-help-text">Dr.Abinisha Kasi</h2>
                            <p class="editorial-description">(MBBS, General Physician)</p>
                            </div>
                       </div>
                       <div class="col-md-3">
                            <div class="doctor-details">
                                <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/doctor-image2.svg'); ?>" alt="Doctor2">
                                <h2 class="editorial-help-text">Dr.Abinisha Kasi</h2>
                                <p class="editorial-description">(MBBS, General Physician)</p>
                            </div>
                       </div>
                       <div class="col-md-3">
                            <div class="doctor-details">
                                <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/doctor-image3.svg'); ?>" alt="Doctor3">
                                <h2 class="editorial-help-text">Dr.Abinisha Kasi</h2>
                                <p class="editorial-description">(MBBS, General Physician)</p>
                            </div>
                       </div>
                       <div class="col-md-3">
                           <div class="doctor-details">
                                <img src="<?php echo $block->getViewFileUrl('MedizinhubCore_Editorial::images/doctor-image4.svg'); ?>" alt="Doctor4">
                                <h2 class="editorial-help-text">Dr.Abinisha Kasi</h2>
                                <p class="editorial-description">(MBBS, General Physician)</p>
                            </div>
                       </div>
                </div>
        </div>
</div>  